### PR TITLE
pkg, cdc: add retry to etcd APIs

### LINKED ISSUE #880: Changefeed is stopped due to PD "raft proposal dropped"
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

TiCDC changefeed is stopped during restarting PD servers. 

```
[2020/08/24 17:06:31.764 +08:00] [ERROR] [processor.go:1058] ["error on running processor"] [captureid=6d0d71b2-53b8-47cb-9dff-0aaf3e735657] [captureaddr=172.16.4.36:8300] [changefeedid=5b3c1158-9516-4049-ba01-0e752edbbe86] [processorid=5409058b-8b79-4bb9-b8cd-be778b6f3052] [error="rpc error: code = Unknown desc = raft proposal dropped"] [errorVerbose="rpc error: code = Unknown desc = raft proposal dropped
github.com/pingcap/errors.AddStack
	github.com/pingcap/errors@v0.11.5-0.20190809092503-95897b64e011/errors.go:174
github.com/pingcap/errors.Trace
	github.com/pingcap/errors@v0.11.5-0.20190809092503-95897b64e011/juju_adaptor.go:15
github.com/pingcap/ticdc/cdc/kv.CDCEtcdClient.PutTaskWorkload
	github.com/pingcap/ticdc@/cdc/kv/etcd.go:496
github.com/pingcap/ticdc/cdc.(*processor).workloadWorker
	github.com/pingcap/ticdc@/cdc/processor.go:467
github.com/pingcap/ticdc/cdc.(*processor).Run.func9
	github.com/pingcap/ticdc@/cdc/processor.go:274
golang.org/x/sync/errgroup.(*Group).Go.func1
	golang.org/x/sync@v0.0.0-20200625203802-6e8e738ad208/errgroup/errgroup.go:57
runtime.goexit
	runtime/asm_amd64.s:1357"]
```

2. What did you expect to see?

Everything works fine.

3. What did you see instead?

Changefeed is stopped.

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        master
        ```

    - TiCDC version (execute `cdc version`):

        ```
        master
        ```

### PR DESCRIPTION
**Pull request by overvenus**
### What problem does this PR solve? 

Add retry to etcd APIs. Resolve #880 

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported variable/fields change

Side effects

 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

### Release note

- No release note.

### CODE REVIEW

File: pkg/etcd/client.go [hunk 1]
```diff
@@ -0,0 +1,110 @@
...
+	// By default, PD etcd sets [3s, 6s) for election timeout.
+	// Some rpc could fail due to etcd errors, like "proposal dropped".
+	// 6.59s = \sum_{n=0}^{4} 0.5*1.5^n
+	return retry.Run(500*time.Millisecond, 4+1, // +1 for the inital request.
+		func() error {
+			err := etcdRPC()
+			if err != nil && errors.Cause(err) != context.Canceled {
+				log.Warn("etcd RPC failed", zap.String("RPC", rpcName), zap.Error(err))
+			}
+			return err
```
Comment (amyangfei) [inline pkg/etcd/client.go:52]: should we return `backoff.Permanent(err)` if cause error is `context.Canceled` directly without retry.

Comment (overvenus) [reply pkg/etcd/client.go:52]: Looks like `Retry()` already has handled `Canceled`

```go
func Run(initialInterval time.Duration, maxRetries uint64, f func() error) error {
	cfg := backoff.NewExponentialBackOff()
	cfg.InitialInterval = initialInterval
	retryCfg := backoff.WithMaxRetries(cfg, maxRetries)
	return backoff.Retry(func() error {
		err := f()
		switch errors.Cause(err) {
		case context.Canceled, context.DeadlineExceeded:
			err = backoff.Permanent(err)
		}
		return err
	}, retryCfg)
}
```

**Comment by leoppro** [comment]
please resolve the conflicts

File: pkg/etcd/client.go [hunk 2]
```diff
@@ -0,0 +1,110 @@
...
+// Unwrap returns a clientv3.Client
+func (c *Client) Unwrap() *clientv3.Client {
+	return c.cli
+}
+
+func retryRPC(rpcName string, etcdRPC func() error) error {
+	// By default, PD etcd sets [3s, 6s) for election timeout.
+	// Some rpc could fail due to etcd errors, like "proposal dropped".
+	// 6.59s = \sum_{n=0}^{4} 0.5*1.5^n
+	return retry.Run(500*time.Millisecond, 4+1, // +1 for the inital request.
```
Comment (5kbpers) [inline pkg/etcd/client.go:46]: Better to increase this timeout to  2 * max_election_timeout, to handle the case that two PDs restarted. (the first election maybe failed)

**Review by leoppro — APPROVED** [review]

**Review by amyangfei — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

**Comment by overvenus** [comment]
/run-integration-tests tidb=release-4.0 tikv=release-4.0 pd=release-4.0

**Comment by leoppro** [comment]
please resolve the conflicts

**Comment by amyangfei** [comment]
/run-integration-tests tidb=release-4.0 tikv=release-4.0 pd=release-4.0

**Comment by amyangfei** [comment]
/run-integration-tests tidb=release-4.0 tikv=release-4.0 pd=release-4.0
