### PR TITLE
kvclient(ticdc): fix kvclient takes too long time to recover

### LINKED ISSUE #3191: kv client takes too long time to recover when a TiKV node shutdowns
### What did you do?

1. Setup a tidb cluster with 5 or more TiKV nodes, and a ticdc replication task, the replicated table should have a large region count, such as 100k or more.
2. Shutdown one of the TiKV node, don't evict leader region before shutdown.
3. Observe how long it takes that the changefeed comes to normal.

### What did you expect to see?

_No response_

### What did you see instead?

image

The kv client takes 23minutes to reconnect all leader regions that belong to the shutdown TiKV, it wastes too much time to retry to establish gPRC connection with the shutdown TiKV store.

```
[2021/10/29 15:26:37.361 +08:00] [INFO] [client.go:377] ["establish stream to store failed, retry later"] [addr=172.16.7.55:20161] [error="[CDC:ErrTiKVEventFeed]rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 172.16.7.55:20161: connect: connection refused\": rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 172.16.7.55:20161: connect: connection refused\""] [errorVerbose="[CDC:ErrTiKVEventFeed]rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 172.16.7.55:20161: connect: connection refused\": rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing 
dial tcp 172.16.7.55:20161: connect: connection refused\"\ngithub.com/pingcap/errors.AddStack\n\tgithub.com/pingcap/errors@v0.11.5-0.20210513014640-40f9a1999b3b/errors.go:174\ngithub.com/pingcap/errors.(*Error).GenWithStackByCause\n\tgithub.com/pingcap/errors@v0.11.5-0.20210513014640-40f9a1999b3b/normalize.go:302\ngithub.com/pingcap/ticdc/pkg/errors.WrapError\n\tgithub.com/pingcap/ticdc/pkg/errors/helper.go:30\ngithub.com/pingcap/ticdc/cdc/kv.(*CDCClient).newStream.func1\n\tgithub.com/pingcap/ticdc/cdc/kv/client.go:376\ngithub.com/pingcap/ticdc/pkg/retry.run\n\tgithub.com/pingcap/ticdc/pkg/retry/retry_with_opt.go:54\ngithub.com/pingcap/ticdc/pkg/retry.Do\n\tgithub.com/pingcap/ticdc/pkg/retry/retry_with_opt.go:32\ngithub.com/pingcap/ticdc/cdc/kv.(*CDCClient).newStream\n\tgithub.com/pingcap/ticdc/cdc/kv/client.go:347\ngithub.com/pingcap/ticdc/cdc/kv.(*eventFeedSession).requestRegionToStore\n\tgithub.com/pingcap/ticdc/cdc/kv/client.go:735\ngithub.com/pingcap/ticdc/cdc/kv.(*eventFeedSession).eventFeed.func2\n\tgithub.com/pingcap/ticdc/cdc/kv/client.go:519\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\tgolang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57\nruntime.goexit\n\truntime/asm_amd64.s:1371"]
```

The kv client should take the available of TiKV store into consideration, which is quite similar to the active store mechanism in region cache.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
v5.2.1
```

TiCDC version (execute `cdc version`):

master@https://github.com/pingcap/ticdc/commit/0a8390ae8e3f6d590b4ed836f960a0332efc6391

### PR DESCRIPTION
**Pull request by maxshuang**
close  #3191 
close flaky test in kvclient: #2694 #3302 #2349  #2688 #2747 

### What problem does this PR solve? 

1. When a tikv node which has 10k region leaders fail, we found it need more than 30min to recover.
2. We think it is abnormal for the reason that pd and tikv only need about 30s to tag a node 'disconnect' and elect a new leader.

### What is changed and how it works?

1. Decrease the retry num when a new stream fail to establish  to make other region try ASAP.
2. Remove PartialClone when the region fail.

#### Reason 
* Expectation
We use a tikv node which has about 3k region leaders as our comparison object. After test in normal case and abnormal case, we got follow results:
```
(1) ~ 1min for 3k region to finish init scan and get event (normal case)
(2) > 20min for all 3k region to recover the stream (tikv node fail)
```
But, pd and tikv only need about 30s to tag a node 'disconnect' and elect a new leader, so a reasonable timespan to recover is about:
```
       1min30s(normal case + region failover) ~ 5min (retry control in cdc)
```

* Consider the probability of network jitter >> tikv temporary down >> tikv permanent down,  we still need some retry logic, so 
```
Decrease the retry num when a new stream fail to establish  to make other region try ASAP.
```
* When a region fail and call RegionCache.OnRegionFail, it will (1) mark the store as 'needcheck' and  fetch new store state of the store asynchronous, (2) move its leader to other peer to try next time and fetch new leader back. This mechanism is suitable in our case, but we find all failed region still connect to the old store which is quite strange.  So we
```
Remove wrong PartialClone logic when the region fail in region_worker.
```

#### Result
```
3min30s to recover from 3k fail (after this pr)  compared to >20min (before) 
```

### Check List 

Tests 
 - Manual test (add detailed scripts or steps below)

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to update key monitor metrics in both TiCDC document and official document

### Release note 

```release-note
Please add a release note.
fix kvclient takes too long time to recover
```

### CODE REVIEW

File: cdc/kv/client.go [hunk 1]
```diff
@@ -1059,10 +1035,12 @@ func (s *eventFeedSession) handleError(ctx context.Context, errInfo regionErrorI
...
 		metricStoreSendRequestErr.Inc()
 	default:
+		//[TODO] Move all OnSendFail logic here
+		// We expect some unknown error to trigger RegionCache recheck its store state and change leader to peer to
+		// make some detection(peer may tell us where new leader is)
+		// RegionCache.OnSendFail is thread_safe inner.
 		bo := tikv.NewBackoffer(ctx, tikvRequestMaxBackoff)
-		if errInfo.rpcCtx.Meta != nil {
-			s.regionCache.OnSendFail(bo, errInfo.rpcCtx, regionScheduleReload, err)
-		}
```
Comment (amyangfei) [inline cdc/kv/client.go:1065]: How can we guarantee `errInfo.rpcCtx.Meta` is not nil?

Comment (maxshuang) [reply cdc/kv/client.go:1065]: 1. errInfo.rpcCtx.Meta is the origin Region object we get from pd, it can not be nil if we always keep rpcCtx as we get from RegionCache.
2. It matter nothing if errInfo.rpcCtx.Meta is nil, because RegionCache.OnSendFail will get *Region from inner cache using RegionVerID. 
3. 'errInfo.rpcCtx.Meta != nil' is related to PartialClone, which I guest is to avoid leader switch(just try), but I think it's unnecessary.

**Review by overvenus — APPROVED** [review]
LGTM

**Review by amyangfei — APPROVED** [review]
