### PR TITLE
*: fix changefeed checkpoint lag negative value error

### LINKED ISSUE #3010: "Changefeed checkpoint lag" displays negative value
### What did you do?

Deploy TiCDC and PD in different hosts, and run changefeed.

"Changefeed checkpoint lag" shows a negative value when hosts clock drifts.

### What did you expect to see?

_No response_

### What did you see instead?

TiCDC metrics dashboard shows "Changefeed checkpoint lag" a negative value.

image

### Versions of the cluster

All TiCDC version.

### PR DESCRIPTION
**Pull request by asddongmen**
### What problem does this PR solve? 

Close #3010 

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)
 - Unit test

Code changes

 - Has exported function/method change
 - Has exported variable/fields change

Side effects

 - Possible performance regression
 - Increased code complexity

Related changes

 - Need to cherry-pick to the release branch

### Release note 

```release-note
fix changefeed checkpoint lag negative value error
```

### CODE REVIEW

File: cdc/owner/changefeed.go [hunk 1]
```diff
@@ -433,7 +432,7 @@ func (c *changefeed) asyncExecDDL(ctx cdcContext.Context, job *timodel.Job) (don
 	return done, nil
 }
 
-func (c *changefeed) updateStatus(barrierTs model.Ts) {
+func (c *changefeed) updateStatus(ctx cdcContext.Context, barrierTs model.Ts) {
```
Comment (overvenus) [inline cdc/owner/changefeed.go:435]:
```suggestion
func (c *changefeed) updateStatus(current model.Ts, barrierTs model.Ts) {
```

Please only pass necessary information.

File: cdc/processor/manager.go [hunk 2]
```diff
@@ -189,6 +199,22 @@ func (m *Manager) handleCommand() error {
...
+	cdcCtx := ctx.(cdcContext.Context)
+	if time.Since(m.lastUpdatedPdTime) <= pdTimeUpdateInterval {
+		return m.pdPhysicalTimeCache, nil
+	}
+	physical, _, err := cdcCtx.GlobalVars().PDClient.GetTS(ctx)
+	if err != nil {
+		return physical, errors.Trace(err)
+	}
+	m.pdPhysicalTimeCache = physical
+	m.lastUpdatedPdTime = time.Now()
```
Comment (overvenus) [inline cdc/processor/manager.go:214]: It's similar to `gcManager.CurrentTimeFromPDCached()`. Could you extract a struct that manages TSO cache?

Comment (asddongmen) [reply cdc/processor/manager.go]: done

File: cdc/owner/changefeed.go (hunk 1 above)
Comment (asddongmen) [reply cdc/owner/changefeed.go:457]: I wil do this lately.

File: cdc/owner/owner.go [hunk 3]
```diff
@@ -22,6 +22,8 @@ import (
 	"sync/atomic"
 	"time"
 
+	"github.com/tikv/client-go/v2/oracle"
+
```
Comment (ben1009) [inline cdc/owner/owner.go:26]: fmt

File: cdc/owner/owner.go [hunk 4]
```diff
@@ -130,8 +132,14 @@ func (o *Owner) Tick(stdCtx context.Context, rawState orchestrator.ReactorState)
...
 	// See more gc doc.
 	if err = o.updateGCSafepoint(stdCtx, state); err != nil {
-		return nil, errors.Trace(err)
+		return state, errors.Trace(err)
+	}
+
+	pdTime, err := o.gcManager.CurrentTimeFromPDCached(ctx)
+	if err != nil {
+		return state, errors.Trace(err)
 	}
```
Comment (amyangfei) [inline cdc/owner/owner.go:141]: Can this error be ignored, this is not a critical path(but error could happen when in `CurrentTimeFromPDCached`. Besides `CurrentTimeFromPDCached` returns `time.Now()` when error happens.

File: cdc/processor/manager.go [hunk 5]
```diff
@@ -19,6 +19,8 @@ import (
 	"io"
 	"time"
 
+	"github.com/tikv/client-go/v2/oracle"
+
```
Comment (amyangfei) [inline cdc/processor/manager.go:23]: Can remove the blank line

File: cdc/owner/owner.go (hunk 4 above)
Comment (asddongmen) [reply cdc/owner/owner.go:141]: good advice~ thinks

File: cdc/owner/changefeed.go (hunk 1 above)
Comment (asddongmen) [reply cdc/owner/changefeed.go:457]: done

File: pkg/util/time_cache.go [hunk 6]
```diff
@@ -0,0 +1,53 @@
...
+import (
+	"context"
+	"time"
+
+	"github.com/pingcap/errors"
+	"github.com/tikv/client-go/v2/oracle"
+	pd "github.com/tikv/pd/client"
+)
+
+const pdTimeUpdateInterval = 1 * time.Second
```
Comment (overvenus) [inline pkg/util/time_cache.go:25]: Could you lower the interval? It can improve accuracy.
```suggestion
const pdTimeUpdateInterval = 200 * time.Millisecond
```

File: pkg/txnutil/gc/gc_manager.go [hunk 7]
```diff
@@ -17,6 +17,8 @@ import (
 	"context"
 	"time"
 
+	"github.com/pingcap/ticdc/pkg/util"
+
```
Comment (overvenus) [inline pkg/txnutil/gc/gc_manager.go:21]:
```suggestion
	"github.com/pingcap/ticdc/pkg/util"
```

File: pkg/context/context.go [hunk 8]
```diff
@@ -38,6 +38,7 @@ type GlobalVars struct {
 	CaptureInfo *model.CaptureInfo
 	EtcdClient  *etcd.CDCEtcdClient
 	GrpcPool    kv.GrpcPool
+	PDPhyTs     int64
```
Comment (overvenus) [inline pkg/context/context.go:41]: It may cause data race, because global var may be accessed in different goroutines.

Could you use `*PDTimeCache` instead? (And `*PDTimeCache` must be thread-safe.)

```suggestion
	PDTime *PDTimeCache
```

File: pkg/util/time_cache.go [hunk 9]
```diff
@@ -0,0 +1,53 @@
...
+// PDTimeCache cache time get from PD client
+type PDTimeCache struct {
+	pdClient            pd.Client
+	pdPhysicalTimeCache time.Time
+	lastUpdatedPdTime   time.Time
+}
+
+// NewPDTimeCache return a new PDTimeCache
+func NewPDTimeCache(pdClient pd.Client) *PDTimeCache {
+	return &PDTimeCache{
```
Comment (overvenus) [inline pkg/util/time_cache.go:36]: Could you spawn a goroutine and let it update `pdPhysicalTimeCache`? By this way, `CurrentTimeFromPDCached` will never block callers.

File: pkg/context/context.go (hunk 8 above)
Comment (asddongmen) [reply pkg/context/context.go:41]: good advice~ thanks

File: pkg/util/time_cache.go (hunk 9 above)
Comment (asddongmen) [reply pkg/util/time_cache.go:41]: done ptal

File: cdc/capture/capture.go [hunk 10]
```diff
@@ -20,6 +20,8 @@ import (
 	"sync"
 	"time"
 
+	"github.com/pingcap/ticdc/pkg/pdtime"
+
 	"github.com/google/uuid"
```
Comment (overvenus) [inline cdc/capture/capture.go:25]:
```suggestion
	"github.com/pingcap/ticdc/pkg/pdtime"
	"github.com/google/uuid"
```

File: pkg/pdtime/acquirer.go [hunk 11]
```diff
@@ -0,0 +1,96 @@
...
+	c.mu.RLock()
+	err := c.err
+	cacheTime := c.timeCache
+	c.mu.RUnlock()
+	return cacheTime, errors.Trace(err)
+}
+
+func (c *TimeAcquirer) Stop() {
+	c.stop <- struct{}{}
+}
```
Comment (overvenus) [inline pkg/pdtime/acquirer.go:96]: Stop should send exit signal and wait goroutine exits.

```suggestion
type TimeAcquirer struct {
	cancel context.CancelFunc
}
func (c *TimeAcquirer) Run(ctx) {
	ctx, cancel := context.WithCancel(ctx)
	defer func() { c.stop <- struct{}{} }()
	......
}
func (c *TimeAcquirer) Stop() {
	c.cancel()
	<-c.stop
}
```

File: pkg/orchestrator/etcd_worker_test.go [hunk 12]
```diff
@@ -272,7 +272,8 @@ func (s *etcdWorkerSuite) TestEtcdSum(c *check.C) {
 	}
 
 	err = errg.Wait()
-	if err != nil && (errors.Cause(err) == context.DeadlineExceeded || errors.Cause(err) == context.Canceled) {
+	if err != nil && (errors.Cause(err) == context.DeadlineExceeded || errors.Cause(err) == context.Canceled ||
```
Comment (overvenus) [inline pkg/orchestrator/etcd_worker_test.go:275]: Please keep line width within 80 chars
```suggestion
	if err != nil && (errors.Cause(err) == context.DeadlineExceeded || 
		errors.Cause(err) == context.Canceled ||
		strings.Contains(err.Error(), "etcdserver: request timeout")) {
```

File: pkg/context/context.go [hunk 13]
```diff
@@ -18,6 +18,8 @@ import (
 	"log"
 	"time"
 
+	"github.com/pingcap/ticdc/pkg/pdtime"
+
 	"github.com/pingcap/ticdc/cdc/kv"
```
Comment (overvenus) [inline pkg/context/context.go:23]:
```suggestion
	"github.com/pingcap/ticdc/pkg/pdtime"
	"github.com/pingcap/ticdc/cdc/kv"
```

File: cdc/owner/changefeed.go [hunk 14]
```diff
@@ -184,7 +184,16 @@ func (c *changefeed) tick(ctx cdcContext.Context, state *orchestrator.Changefeed
 		return errors.Trace(err)
 	}
 	if shouldUpdateState {
-		c.updateStatus(barrierTs)
+		pdTime := time.Now()
+		// only nil in test
+		if ctx.GlobalVars().TimeAcquirer != nil {
```
Comment (overvenus) [inline cdc/owner/changefeed.go:189]: Could you set TimeAcquirer in tests? So we can keep code a bit tidier.

File: pkg/txnutil/gc/gc_manager.go [hunk 15]
```diff
@@ -111,27 +107,21 @@ func (m *gcManager) TryUpdateGCSafePoint(
...
 func (m *gcManager) CheckStaleCheckpointTs(
 	ctx context.Context, changefeedID model.ChangeFeedID, checkpointTs model.Ts,
 ) error {
 	gcSafepointUpperBound := checkpointTs - 1
 	if m.isTiCDCBlockGC {
-		pdTime, err := m.CurrentTimeFromPDCached(ctx)
-		if err != nil {
-			return errors.Trace(err)
+		cctx := ctx.(cdcContext.Context)
+		pdTime := time.Now()
```
Comment (overvenus) [inline pkg/txnutil/gc/gc_manager.go:116]: Type assertion without ok check may cause panic.

**Review by overvenus — APPROVED** [review]
LGTM

**Review by ben1009 — APPROVED** [review]

**Comment by amyangfei** [comment]
`make check` failed
