### PR TITLE
cdc/sink: adjust kafka initialization logic

### LINKED ISSUE #3337: [ticdc 5.3.0] kafka changefeed error: kafka server: Message was too large
### What did you do?

-here's kafka topic server.log: image

- upgrade tidb cluster from 5.2.1 to 5.3.0

- remove all changefeed, than create 2 new changefeeds: tiup ctl:v5.3.0 cdc changefeed create --pd=http://172.16.4.158:2379 --sink-uri="mysql://root:123456@172.16.6.35:35002/"  --changefeed-id="mysql-task-1" ;tiup ctl:v5.3.0 cdc changefeed create --pd=http://172.16.4.158:2379 --sink-uri='kafka://172.16.6.24:9092/cdc-events?'  --changefeed-id="kafka-task-1"
- Run workload:go-tpc tpcc --db workload --warehouses 20 -T 20 --host 172.16.4.158 --port 4000 --parts 1 prepare
- kafka topic cdc-events has 6 partitions, max.message.bytes -> 1000012

### What did you expect to see?

_No response_

### What did you see instead?

 "id": "kafka-task-1",
    "summary": {
      "state": "error",
      "tso": 428963091419234305,
      "checkpoint": "2021-11-08 17:38:51.891",
      "error": {
        "addr": "172.16.4.158:8300",
        "code": "CDC:ErrProcessorUnknown",
        "message": "[CDC:ErrKafkaAsyncSendMessage]kafka: Failed to produce message to topic cdc-events: kafka server: Message was too large, server rejected it to avoid allocation error.: kafka: Failed to produce message to topic cdc-events: kafka server: Message was too large, server rejected it to avoid allocation error."
      }
    }
  }
]

- kafka changefeed error and won't sync data.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```
elease Version: v5.3.0
Edition: Community
Git Commit Hash: e401a0606bf84214bd8e765295ec6cfadd9ba24e
Git Branch: heads/refs/tags/v5.3.0
UTC Build Time: 2021-11-08 04:40:23
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |```

TiCDC version (execute `cdc version`):

```
./cdc version
Release Version: v5.3.0
Git Commit Hash: 7dc044edd1a894c4e6846c27673069ccfc920d56
Git Branch: heads/refs/tags/v5.3.0
UTC Build Time: 2021-11-08 04:37:11
Go Version: go version go1.16.4 linux/amd64
Failpoint Build: false```

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### What problem does this PR solve? 

close #3337

This is part work of making Kafka GA. Contain the following:
* Refine the logic of creating topic
* Make some variable become a field of the `Config`, which would be helpful if we would support one producer per topic in the future since this group producer parameters together.
* Bugfix
  * If `auto-create-topic` disable by the user, the partition count will not be checked.
  * before create the topic, make sure broker's `message.max.bytes` not less than `max-message-bytes`

### Check List 

Tests 

 - Unit test
 - Manual test (add detailed scripts or steps below)
Screen Shot 2021-11-09 at 13 24 36

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to update key monitor metrics in both TiCDC document and official document

### Release note 

```release-note
Please add a release note.
If you don't think this PR needs a release note then fill it with `None`.
```

### CODE REVIEW

File: cdc/sink/producer/kafka/kafka.go [hunk 1]
```diff
@@ -64,12 +69,21 @@ func NewConfig() *Config {
...
+		AutoCreate:        true,
 	}
 }
 
 // Initialize the kafka configuration
 func (c *Config) Initialize(sinkURI *url.URL, replicaConfig *config.ReplicaConfig, opts map[string]string) error {
+	c.BrokerEndpoints = strings.Split(sinkURI.Host, ",")
+	topic := strings.TrimFunc(sinkURI.Path, func(r rune) bool {
+		return r == '/'
+	})
```
Comment (overvenus) [inline cdc/sink/producer/kafka/kafka.go:81]: Could you add some comments? Is it a bugfix?

File: cdc/sink/producer/kafka/kafka.go [hunk 2]
```diff
@@ -395,80 +409,120 @@ func (k *kafkaSaramaProducer) run(ctx context.Context) error {
 	}
 }
 
-// kafkaTopicPreProcess gets partition number from existing topic, if topic doesn't
-// exit, creates it automatically.
-func kafkaTopicPreProcess(topic, address string, config *Config, cfg *sarama.Config) (int32, error) {
-	admin, err := sarama.NewClusterAdmin(strings.Split(address, ","), cfg)
+func topicPreProcess(config *Config, saramaConfig *sarama.Config) error {
+	failpoint.Inject("workaround4Test", func() {
```
Comment (overvenus) [inline cdc/sink/producer/kafka/kafka.go:413]: Could you avoid failpoints in unit tests? Can it be replaced by mocking `topicPreProcess`?

File: cdc/sink/producer/kafka/kafka.go [hunk 3]
```diff
@@ -550,7 +604,9 @@ func newSaramaConfig(ctx context.Context, c *Config) (*sarama.Config, error) {
 	}
 	config.Version = version
 	// See: https://kafka.apache.org/documentation/#replication
-	// When one of the brokers in a Kafka cluster is down, the partition leaders in this broker is broken, Kafka will election a new partition leader and replication logs, this process will last from a few seconds to a few minutes. Kafka cluster will not provide a writing service in this process.
+	// When one of the brokers in a Kafka cluster is down, the partition leaders in this broker is broken,
+	// Kafka will election a new partition leader and replication logs, this process will last from a few seconds to a few minutes.
```
Comment (overvenus) [inline cdc/sink/producer/kafka/kafka.go:608]: Please keep line width within 80 chars.
  
```suggestion
	// When one of the brokers in a Kafka cluster is down, the partition leaders
	// in this broker is broken, Kafka will election a new partition leader and
	// replication logs, this process will last from a few seconds to a few
	// minutes.
```

File: cdc/sink/producer/kafka/kafka.go [hunk 4]
```diff
@@ -395,80 +409,120 @@ func (k *kafkaSaramaProducer) run(ctx context.Context) error {
...
+		return err
+	}
+
+	var realPartitionCount int32 = 0
+	info, ok := topics[config.TopicName]
+	if ok {
+		realPartitionCount = info.NumPartitions
+	}
+
+	// if user specify cdc to create the topic, we must make sure that `partition-num` and `replication-factor` is given
```
Comment (overvenus) [inline cdc/sink/producer/kafka/kafka.go:437]: Please keep line width within 80 chars.

File: cdc/sink/producer/kafka/kafka.go (hunk 1 above)
Comment (3AceShowHand) [reply cdc/sink/producer/kafka/kafka.go:81]: no, this only move the topic name into the config.

If we would support multiple producers in the future, this is helpful, since we can construct different configs for different topics.

File: cdc/sink/producer/kafka/kafka.go (hunk 2 above)
Comment (3AceShowHand) [reply cdc/sink/producer/kafka/kafka.go:413]: It was quite hard to mock this method, since this method is defined in the package `sink/kafka`, but will also be called by unit test in the `sink` package.

If try to mock the method, have to make this method public, I think it's unreasonable.

failpoint would be the easiest way to workaround this.

Comment (liuzix) [reply cdc/sink/producer/kafka/kafka.go:413]: Maybe we can leave a `FIXME` here for now?

File: cdc/sink/producer/kafka/kafka.go [hunk 5]
```diff
@@ -395,80 +409,121 @@ func (k *kafkaSaramaProducer) run(ctx context.Context) error {
...
+		realPartitionCount = info.NumPartitions
+	}
+
+	// if user specify cdc to create the topic, we must make sure
+	// that `partition-num` and `replication-factor` is given
+	if config.AutoCreate {
+		// if the specified topic name already exist, we should make sure that
+		// topic's `max.message.bytes` is not less than given `max-message-size`
+		if ok {
+			if a, ok := info.ConfigEntries["max.message.bytes"]; ok {
```
Comment (liuzix) [inline cdc/sink/producer/kafka/kafka.go:443]: Do we need to check `max.request.size`?

File: cdc/sink/producer/kafka/kafka.go [hunk 6]
```diff
@@ -395,80 +409,121 @@ func (k *kafkaSaramaProducer) run(ctx context.Context) error {
...
+				topicMaxMessageBytes, err := strconv.Atoi(*a)
+				if err != nil {
+					return err
```
Comment (liuzix) [inline cdc/sink/producer/kafka/kafka.go:446]: Please wrap the error so that the user has a basic idea how it happens.

File: cdc/sink/producer/kafka/kafka.go [hunk 7]
```diff
@@ -395,80 +409,121 @@ func (k *kafkaSaramaProducer) run(ctx context.Context) error {
...
+				}
+				if topicMaxMessageBytes < config.MaxMessageBytes {
+					return cerror.ErrKafkaInvalidConfig.GenWithStack(
+						"topic already exist, and max.message.size(%d) less than max-message-size(%d)",
```
Comment (liuzix) [inline cdc/sink/producer/kafka/kafka.go:450]: Leave a short hint for user to fix?

File: cdc/sink/producer/kafka/kafka.go [hunk 8]
```diff
@@ -395,80 +409,121 @@ func (k *kafkaSaramaProducer) run(ctx context.Context) error {
...
+			config.PartitionNum = realPartitionCount
+			log.Warn("topic already exist", zap.String("topic", config.TopicName))
+			return nil
 		}
-	} else {
-		if partitionNum == 0 {
-			partitionNum = defaultPartitionNum
-			log.Warn("topic not found and partition number is not specified, using default partition number", zap.String("topic", topic), zap.Int32("partition_num", partitionNum))
+		// this could happen if user does not specify the `partition-num` in the sink uri.
+		if config.PartitionNum == 0 {
```
Comment (liuzix) [inline cdc/sink/producer/kafka/kafka.go:460]: Is it acceptable if the user specifies `partition-num=0`?

File: cdc/sink/producer/kafka/kafka.go [hunk 9]
```diff
@@ -395,80 +409,121 @@ func (k *kafkaSaramaProducer) run(ctx context.Context) error {
...
+		return cerror.ErrKafkaInvalidConfig.GenWithStack("auto-create-topic is false, and topic not found")
+	}
+
+	if config.PartitionNum == 0 {
+		config.PartitionNum = realPartitionCount
+		return nil
+	}
+
+	if config.PartitionNum < realPartitionCount {
+		log.Warn("partition count assigned in sink-uri is less than that of topic, some partitions would not have messages to be dispatched",
```
Comment (liuzix) [inline cdc/sink/producer/kafka/kafka.go:491]:
```suggestion
		log.Warn("number of partition specified in sink-uri is less than that of the actual topic. Some partitions will not have messages dispatched to",
```

File: cdc/sink/producer/kafka/kafka.go [hunk 10]
```diff
@@ -395,80 +409,121 @@ func (k *kafkaSaramaProducer) run(ctx context.Context) error {
...
+			zap.Int32("sink-uri partitions", config.PartitionNum), zap.Int32("topic partitions", realPartitionCount))
+		return nil
+	}
+
+	// for topic already exist, we just make sure that the user specified partition count is not greater than the real
```
Comment (liuzix) [inline cdc/sink/producer/kafka/kafka.go:496]:
```suggestion
	// For topic already existing, we just make sure that the user-specified partition count is not greater than the real
```

File: cdc/sink/producer/kafka/kafka.go [hunk 11]
```diff
@@ -395,80 +409,121 @@ func (k *kafkaSaramaProducer) run(ctx context.Context) error {
...
+	// partition count, since we would dispatch messages to different partitions, this could prevent potential message loss.
```
Comment (liuzix) [inline cdc/sink/producer/kafka/kafka.go:497]: Please reword this sentence. `since we would dispatch messages to different partitions` does not have a clear meaning.

File: cdc/sink/producer/kafka/kafka.go [hunk 12]
```diff
@@ -395,80 +409,121 @@ func (k *kafkaSaramaProducer) run(ctx context.Context) error {
...
+	if config.PartitionNum > realPartitionCount {
+		return cerror.ErrKafkaInvalidPartitionNum.GenWithStack(
+			"partition number(%d) assigned in sink-uri is more than that of topic(%d)", config.PartitionNum, realPartitionCount)
```
Comment (liuzix) [inline cdc/sink/producer/kafka/kafka.go:500]:
```suggestion
			"the number of partition (%d) specified in sink-uri is more than that of actual topic (%d)", config.PartitionNum, realPartitionCount)
```

File: cdc/sink/producer/kafka/kafka.go (hunk 8 above)
Comment (3AceShowHand) [reply cdc/sink/producer/kafka/kafka.go:460]: this could happen if the user does not specify the `partition-num`, which would be 0.

Comment (liuzix) [reply cdc/sink/producer/kafka/kafka.go:460]: Is it checked that the user does not specified `partition-num=0`?

File: cdc/sink/producer/kafka/kafka.go [hunk 13]
```diff
@@ -37,11 +37,16 @@ import (
 	"go.uber.org/zap"
 )
 
-const defaultPartitionNum = 4
+const defaultPartitionNum = 3
```
Comment (amyangfei) [inline cdc/sink/producer/kafka/kafka.go:40]: Why is this value changed?

Comment (3AceShowHand) [reply cdc/sink/producer/kafka/kafka.go:40]: 1. we would use partition-num as the mod for partition dispatch, and `3` is a prime number, much better for hash
2. `3` is a much more reasonable number for replication, and as I know, Kafka would use `KRaft` for consistency protocol, it's good for `raft`
3. `3` would consume less memory usage.

File: cdc/sink/producer/kafka/kafka.go (hunk 5 above)
Comment (3AceShowHand) [reply cdc/sink/producer/kafka/kafka.go:444]: `max.request.size` is a producer level configuration.
I think when creating the sarama producer, it's `MaxMessageBytes` is for this.

File: cdc/sink/producer/kafka/kafka.go [hunk 14]
```diff
@@ -395,80 +400,127 @@ func (k *kafkaSaramaProducer) run(ctx context.Context) error {
 	}
 }
 
-// kafkaTopicPreProcess gets partition number from existing topic, if topic doesn't
-// exit, creates it automatically.
-func kafkaTopicPreProcess(topic, address string, config *Config, cfg *sarama.Config) (int32, error) {
-	admin, err := sarama.NewClusterAdmin(strings.Split(address, ","), cfg)
+func topicPreProcess(topic string, config *Config, saramaConfig *sarama.Config) error {
+	// FIXME: find a way to remove this failpoint for workload the unit test
+	failpoint.Inject("workaround4Test", func() {
```
Comment (amyangfei) [inline cdc/sink/producer/kafka/kafka.go:405]: Better to rename failpoint injection to `SkipTopicAutoCreate`

File: cdc/sink/producer/kafka/kafka.go [hunk 15]
```diff
@@ -395,80 +400,127 @@ func (k *kafkaSaramaProducer) run(ctx context.Context) error {
...
+		failpoint.Return(nil)
+	})
+	admin, err := sarama.NewClusterAdmin(config.BrokerEndpoints, saramaConfig)
 	if err != nil {
-		return 0, cerror.WrapError(cerror.ErrKafkaNewSaramaProducer, err)
+		return err
```
Comment (amyangfei) [inline cdc/sink/producer/kafka/kafka.go:410]: Should wrap `err` with an RFC error

File: cdc/sink/producer/kafka/kafka.go [hunk 16]
```diff
@@ -395,80 +400,127 @@ func (k *kafkaSaramaProducer) run(ctx context.Context) error {
...
+				}
+				if topicMaxMessageBytes < config.MaxMessageBytes {
+					return cerror.ErrKafkaInvalidConfig.GenWithStack(
+						"topic already exist, and max.message.size(%d) less than max-message-size(%d)."+
+							"Please make sure max-message-size not greater than topic max.message.size",
+						topicMaxMessageBytes, config.MaxMessageBytes)
+				}
+			}
+
+			config.PartitionNum = realPartitionCount
```
Comment (amyangfei) [inline cdc/sink/producer/kafka/kafka.go:448]: Is `realPartitionCount` zero when no topic exists before?

File: cdc/sink/producer/kafka/kafka.go [hunk 17]
```diff
@@ -395,80 +400,127 @@ func (k *kafkaSaramaProducer) run(ctx context.Context) error {
...
+		realPartitionCount = info.NumPartitions
+	}
+
+	// if user specify cdc to create the topic, we must make sure
+	// that `partition-num` and `replication-factor` is given
+	if config.AutoCreate {
+		// if the specified topic name already exist, we should make sure that
+		// topic's `max.message.bytes` is not less than given `max-message-size`
+		if ok {
+			if a, ok := info.ConfigEntries["max.message.bytes"]; ok {
```
Comment (amyangfei) [inline cdc/sink/producer/kafka/kafka.go:435]: `info` could be nil

File: cdc/sink/producer/kafka/kafka.go (hunk 16 above)
Comment (amyangfei) [reply cdc/sink/producer/kafka/kafka.go:448]: ignore this

File: cdc/sink/producer/kafka/kafka.go [hunk 18]
```diff
@@ -395,80 +400,127 @@ func (k *kafkaSaramaProducer) run(ctx context.Context) error {
...
+		return nil
+	}
+
+	// if `auto-create-topic` is disabled by user, we would assume topic should have already created
+	if !ok {
+		return cerror.ErrKafkaInvalidConfig.GenWithStack("auto-create-topic is false, and topic not found")
+	}
+
+	if config.PartitionNum == 0 {
+		config.PartitionNum = realPartitionCount
```
Comment (amyangfei) [inline cdc/sink/producer/kafka/kafka.go:479]: `realPartitionCount` could be zero here?

File: cdc/sink/producer/kafka/kafka.go [hunk 19]
```diff
@@ -395,80 +400,127 @@ func (k *kafkaSaramaProducer) run(ctx context.Context) error {
...
+	if config.AutoCreate {
+		// if the specified topic name already exist, we should make sure that
+		// topic's `max.message.bytes` is not less than given `max-message-size`
+		if ok {
+			if a, ok := info.ConfigEntries["max.message.bytes"]; ok {
+				topicMaxMessageBytes, err := strconv.Atoi(*a)
+				if err != nil {
+					return cerror.WrapError(cerror.ErrKafkaNewSaramaProducer, err)
+				}
+				if topicMaxMessageBytes < config.MaxMessageBytes {
```
Comment (amyangfei) [inline cdc/sink/producer/kafka/kafka.go:440]: Do we also need to check max message bytes when topic exists and `AutoCreate` is false?

File: cdc/sink/producer/kafka/kafka.go (hunk 16 above)
Comment (amyangfei) [inline cdc/sink/producer/kafka/kafka.go:448]: The original logic, if `partition-num` in sink-uri is larger than 0, and less than the partition number of existing topic, will set `config.PartitionNum = partition num in sink uri`, seems the behavior is changed here?

File: cdc/sink/producer/kafka/kafka.go [hunk 20]
```diff
@@ -395,80 +400,127 @@ func (k *kafkaSaramaProducer) run(ctx context.Context) error {
...
 			ReplicationFactor: config.ReplicationFactor,
+			ConfigEntries: map[string]*string{
+				"max.message.bytes": &maxMessageBytes,
+			},
 		}, false)
-		// TODO idenfity the cause of "Topic with this name already exists"
+		// TODO identify the cause of "Topic with this name already exists"
 		if err != nil && !strings.Contains(err.Error(), "already exists") {
-			return 0, cerror.WrapError(cerror.ErrKafkaNewSaramaProducer, err)
+			return err
```
Comment (amyangfei) [inline cdc/sink/producer/kafka/kafka.go:468]: Should use `cerror.WrapError(cerror.ErrKafkaNewSaramaProducer, err)`

File: cdc/sink/producer/kafka/kafka.go (hunk 18 above)
Comment (3AceShowHand) [reply cdc/sink/producer/kafka/kafka.go:479]: If the user does not specify `partition-num` in the sink uri, it will be 0, which means uninitialized.

Comment (amyangfei) [reply cdc/sink/producer/kafka/kafka.go:479]: Well, it must be `AutoCreate == false` and topic exists when running at L479.
Can we extract several independent part, such as
- determine and check config.PartitionNum
- create topic if needed
- check max message bytes if needed

File: cdc/sink/producer/kafka/kafka.go (hunk 8 above)
Comment (3AceShowHand) [reply cdc/sink/producer/kafka/kafka.go:449]: we have check `partition-num` in https://github.com/pingcap/ticdc/blob/master/cdc/sink/producer/kafka/kafka.go#L74

But if they does not pass `partition-num` in the sink-uri, it would be 0.

**Review by overvenus — APPROVED** [review]
LGTM

File: cdc/sink/producer/kafka/kafka.go [hunk 21]
```diff
@@ -395,80 +399,122 @@ func (k *kafkaSaramaProducer) run(ctx context.Context) error {
...
-		err := admin.CreateTopic(topic, &sarama.TopicDetail{
-			NumPartitions:     partitionNum,
-			ReplicationFactor: config.ReplicationFactor,
-		}, false)
-		// TODO idenfity the cause of "Topic with this name already exists"
-		if err != nil && !strings.Contains(err.Error(), "already exists") {
-			return 0, cerror.WrapError(cerror.ErrKafkaNewSaramaProducer, err)
+
+		if err := config.adjustPartitionNum(info.NumPartitions); err != nil {
+			return cerror.WrapError(cerror.ErrKafkaNewSaramaProducer, err)
```
Comment (amyangfei) [inline cdc/sink/producer/kafka/kafka.go:448]: Better to `return err` directly, since the `err` returned from `config.adjustPartitionNum` is already an RFC error

File: cdc/sink/producer/kafka/kafka.go [hunk 22]
```diff
@@ -395,80 +399,122 @@ func (k *kafkaSaramaProducer) run(ctx context.Context) error {
...
+		return cerror.ErrKafkaInvalidConfig.GenWithStack("`auto-create-topic` is false, and topic not found")
+	}
+
+	// when try to create the topic, we don't know how to set the `max.message.bytes` for the topic.
+	// Kafka would create the topic with broker's `message.max.bytes`,
+	// we have to make sure it's not greater than `max-message-bytes`
+	brokerMessageMaxBytes, err := getBrokerMessageMaxBytes(admin)
+	if err != nil {
+		log.Warn("TiCDC cannot find `message.max.bytes` from broker's configuration")
+		return cerror.WrapError(cerror.ErrKafkaNewSaramaProducer, err)
```
Comment (amyangfei) [inline cdc/sink/producer/kafka/kafka.go:464]: ditto, it is better to return RFC error from function `getBrokerMessageMaxBytes`

File: cdc/sink/producer/kafka/kafka.go [hunk 23]
```diff
@@ -395,80 +399,122 @@ func (k *kafkaSaramaProducer) run(ctx context.Context) error {
...
+	if config.PartitionNum == 0 {
+		config.PartitionNum = defaultPartitionNum
+		log.Warn("partition-num is not set, use the default partition count",
+			zap.String("topic", topic), zap.Int32("partitions", config.PartitionNum))
+	}
+
+	err = admin.CreateTopic(topic, &sarama.TopicDetail{
+		NumPartitions:     config.PartitionNum,
+		ReplicationFactor: config.ReplicationFactor,
+	}, false)
```
Comment (amyangfei) [inline cdc/sink/producer/kafka/kafka.go:484]: Do we need to pass the `max.message.bytes` config here?

Comment (3AceShowHand) [reply cdc/sink/producer/kafka/kafka.go:484]: no, let broker decide the value.

**Review by amyangfei — APPROVED** [review]

File: cdc/sink/mq.go [hunk 24]
```diff
@@ -393,7 +393,13 @@ func newKafkaSaramaSink(ctx context.Context, sinkURI *url.URL, filter *filter.Fi
 	topic := strings.TrimFunc(sinkURI.Path, func(r rune) bool {
 		return r == '/'
 	})
-	producer, err := kafka.NewKafkaSaramaProducer(ctx, sinkURI.Host, topic, config, errCh)
+	if topic == "" {
+		return nil, cerror.ErrKafkaInvalidConfig.GenWithStack("topic name not found")
```
Comment (liuzix) [inline cdc/sink/mq.go:397]:
```suggestion
		return nil, cerror.ErrKafkaInvalidConfig.GenWithStack("no topic is specified in sink-uri")
```

**Review by liuzix — COMMENTED** [review]
rest LGTM

**Review by liuzix — APPROVED** [review]
