### PR TITLE
dispatcher: fix checkpoint report to eventService

### LINKED ISSUE #3619: fix slow dispatcher log in eventService
as title

### PR DESCRIPTION
**Pull request by asddongmen**
### What problem does this PR solve?

Issue Number: close #3619 

#### Tests 

- Manual test (add detailed scripts or steps below)

### Release note 

```release-note
None
```

### CODE REVIEW

File: downstreamadapter/dispatchermanager/dispatcher_manager.go [hunk 1]
```diff
@@ -712,13 +712,20 @@ func (e *DispatcherManager) aggregateDispatcherHeartbeats(needCompleteStatus boo
...
+				if watermark != nil {
+					eventServiceDispatcherHeartbeat.Append(event.NewDispatcherProgress(id, watermark.CheckpointTs))
+				}
 			})
 		}
-		e.dispatcherMap.ForEach(func(id common.DispatcherID, dispatcher *dispatcher.EventDispatcher) {
-			eventServiceDispatcherHeartbeat.Append(event.NewDispatcherProgress(id, message.Watermark.CheckpointTs))
+		e.dispatcherMap.ForEach(func(id common.DispatcherID, dispatcherItem *dispatcher.EventDispatcher) {
+			_, _, watermark := getDispatcherStatus(id, dispatcherItem, needCompleteStatus)
+			if watermark != nil {
```
Comment (wk989898) [inline downstreamadapter/dispatchermanager/dispatcher_manager.go]: If the watermark is nil, will the dispatcher send a progress?

**Review by wk989898 — APPROVED** [review]

**Review by hongyunyan — APPROVED** [review]
