### PR TITLE
http: fix the api capture list output does not match the old architecture

### LINKED ISSUE #1241: http open api capture list output does not match the previous implementation.
Image

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### What problem does this PR solve?

Issue Number: close #1241 

#### Tests 

- Unit test
- Integration test

### Release note 

```release-note
`None`
```

### CODE REVIEW

**Review by asddongmen — APPROVED** [review]

File: api/v2/model.go [hunk 1]
```diff
@@ -1185,9 +1185,9 @@ type Capture struct {
 	ID string `json:"id"`
 	// IsCoordinator is true if the capture is the coordinator of the TiCDC cluster
 	// We make its json key as `is_owner` to keep the compatibility with old TiCDC.
```
Comment (asddongmen) [inline api/v2/model.go:1187]: Please also change this comment.

Comment (3AceShowHand) [inline api/v2/model.go:1187]:
```suggestion
	// We make its json key as `is-owner` to keep the compatibility with old TiCDC.
```
