### PR TITLE
relay, syncer(dm): stricter GTID check when retry replication

### LINKED ISSUE #3487: data lost in chaos with enable-relay
### What did you do?

***Background***
chaos disabled relay after v2.0.2
enable after https://github.com/pingcap/ticdc/pull/3190

***source1***
```
enable-relay: true
enable-gtid: true
```

***error found in worker.log***
```
[2021/11/16 12:50:43.768 +00:00] [INFO] [syncer.go:2368] ["skip event, need handled ddls is empty"] [task=task_single] [unit="binlog replication"] [event=query] [queryEventContext="{schema: db_optimistic, originSQL: ALTER TABLE db_optimistic.ddtgdgdix DROP INDEX case8_idx, startLocation: position: (mysql-bin|000001.000003, 50715508), gtid-set: f70af929-46da-11ec-9807-52834c88734c:1-6584, currentLocation: position: (mysql-bin|000001.000003, 50715656), gtid-set: f70af929-46da-11ec-9807-52834c88734c:1-6585, lastLocation: position: (mysql-bin|000001.000003, 50715656), gtid-set: f70af929-46da-11ec-9807-52834c88734c:1-6585, re-sync: , needHandleDDLs: , trackInfos: }"]
[2021/11/16 12:50:43.770 +00:00] [WARN] [local_reader.go:559] ["fail to parse relay log file, meet some ignorable error"] [task=task_single] [unit="binlog replication"] [component="binlog reader"] [file=relay-dir/f70af929-46da-11ec-9807-52834c88734c.000001/mysql-bin.000003] [offset=50723867] [error="get event err EOF, need 8099 but got 978"] [errorVerbose="get event err EOF, need 8099 but got 978\ngithub.com/go-mysql-org/go-mysql/replication.(*BinlogParser).parseSingleEvent\n\tgithub.com/go-mysql-org/go-mysql@v1.1.3-0.20210705101833-83965e516929/replication/parser.go:130\ngithub.com/go-mysql-org/go-mysql/replication.(*BinlogParser).ParseReader\n\tgithub.com/go-mysql-org/go-mysql@v1.1.3-0.20210705101833-83965e516929/replication/parser.go:165\ngithub.com/go-mysql-org/go-mysql/replication.(*BinlogParser).ParseFile\n\tgithub.com/go-mysql-org/go-mysql@v1.1.3-0.20210705101833-83965e516929/replication/parser.go:96\ngithub.com/pingcap/ticdc/dm/relay.(*BinlogReader).parseFile\n\tgithub.com/pingcap/ticdc/dm/relay/local_reader.go:556\ngithub.com/pingcap/ticdc/dm/relay.(*BinlogReader).parseFileAsPossible\n\tgithub.com/pingcap/ticdc/dm/relay/local_reader.go:413\ngithub.com/pingcap/ticdc/dm/relay.(*BinlogReader).parseDirAsPossible\n\tgithub.com/pingcap/ticdc/dm/relay/local_reader.go:382\ngithub.com/pingcap/ticdc/dm/relay.(*BinlogReader).parseRelay\n\tgithub.com/pingcap/ticdc/dm/relay/local_reader.go:311\ngithub.com/pingcap/ticdc/dm/relay.(*BinlogReader).StartSyncByGTID.func1\n\tgithub.com/pingcap/ticdc/dm/relay/local_reader.go:284\nruntime.goexit\n\truntime/asm_amd64.s:1371"]
[2021/11/16 12:50:43.771 +00:00] [ERROR] [streamer_controller.go:287] ["meet error when get binlog event"] [task=task_single] [unit="binlog replication"] [error="truncate binlog file found, event may be duplicated"] [errorVerbose="truncate binlog file found, event may be duplicated\ngithub.com/pingcap/ticdc/dm/relay.init\n\tgithub.com/pingcap/ticdc/dm/relay/local_reader.go:44\nruntime.doInit\n\truntime/proc.go:6265\nruntime.doInit\n\truntime/proc.go:6242\nruntime.doInit\n\truntime/proc.go:6242\nruntime.main\n\truntime/proc.go:208\nruntime.goexit\n\truntime/asm_amd64.s:1371"]
[2021/11/16 12:50:43.771 +00:00] [WARN] [syncer.go:1647] ["read binlog met a truncated file, need to open safe-mode until the next transaction"] [task=task_single] [unit="binlog replication"]
[2021/11/16 12:50:43.771 +00:00] [INFO] [syncer.go:1571] ["discard event already consumed"] [count=1] [cur_loc="position: (mysql-bin|000001.000003, 50723867), gtid-set: f70af929-46da-11ec-9807-52834c88734c:1-6586"]
[2021/11/16 12:50:43.992 +00:00] [INFO] [ddl.go:36] ["parse ddl"] [task=task_single] [unit="binlog replication"] [event=query] ["query event context"="{schema: db_optimistic, originSQL: ALTER TABLE db_optimistic.ddtgdgdix ADD INDEX case8_idx(case4_flag1, case4_flag2, case4_flag3), startLocation: position: (mysql-bin|000001.000003, 50806363), gtid-set: f70af929-46da-11ec-9807-52834c88734c:1-6603, currentLocation: position: (mysql-bin|000001.000003, 50806549), gtid-set: f70af929-46da-11ec-9807-52834c88734c:1-6604, lastLocation: position: (mysql-bin|000001.000003, 50806298), gtid-set: f70af929-46da-11ec-9807-52834c88734c:1-6603, re-sync: , needHandleDDLs: , trackInfos: }"]
```
we can see that task is normal at f70af929-46da-11ec-9807-52834c88734c:1-6585

gtid:6586 is a delete event with multiple rows
```
3341
3342
3343
3345
3347
3348
3349
3350
3355
3357
3358
3359
3360
3362
3363
3364
3365
3366
3368
3369
3371
3373
3379
3382
3386
3387
3389
3394
3395
3396
3402
3403
3406
3407
3408
3409
3410
3411
3412
3413
3414
3415
3416
3417
3418
3419
3420
3421
3422
3423
3424
3425
3426
3427
3428
3429
3430
3431
3432
3433
3434
3435
3436
```

I found downstream doesn't delete
```
3395
3396
3402
3403
3406
3407
3408
3409
3410
3411
3412
3413
3414
3415
3416
3417
3418
3419
3420
3421
3422
3423
3424
3425
3426
3427
3428
3429
```
So we lost the data after error `truncate binlog file found, event may be duplicated`

### What did you expect to see?

task runs well

### What did you see instead?

lost data

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
master
```

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve? 

close #3487 

also avoid skipping events of another GTID after re-connect upstream without relay. when upstream switches, we continue from last finished GTID set, but new upstream may send different GTID (maybe written from itself rather than the replication master)

### What is changed and how it works?

- relay only send ErrMaybeDuplicateEvent when upstream switch and last relay log file is not properly closed
- when syncer want to skip part of transaction, it should check GTID first

### Check List 

Tests 

 - Integration test
 - Chaos
   all errors are not related to DML error

   actions https://github.com/pingcap/ticdc/runs/4362245853?check_suite_focus=true failed
   actions https://github.com/pingcap/ticdc/actions/runs/1528934575 failed
   reason: https://github.com/pingcap/ticdc/issues/3604

   actions https://github.com/pingcap/ticdc/runs/4362511775?check_suite_focus=true pass

   actions https://github.com/pingcap/ticdc/runs/4362769688?check_suite_focus=true failed
   `add column case1 that wasn't fully dropped in downstream`

   actions https://github.com/pingcap/ticdc/runs/4365073556?check_suite_focus=true failed
   `index num not equal, one is 2 another is 1`

   actions https://github.com/pingcap/ticdc/actions/runs/1524386743 failed
   `index num not equal, one is 2 another is 1`
   `column num not equal, one is 28 another is 25`

Code changes

 - Has exported function/method change

Side effects

Related changes

 - Need to cherry-pick to the release branch

### Release note 

```release-note
When auto recover a GTID replication, skip duplicated events of unfinished transaction.
```

### CODE REVIEW

**Comment by lance6716** [comment]
actions https://github.com/pingcap/ticdc/runs/4362245853?check_suite_focus=true failed

reason: https://github.com/pingcap/ticdc/issues/3604

**Comment by lance6716** [comment]
I'm keep re-running github actions, now I think it's OK to review 

/cc @GMHDBJD @glorv @D3Hunter

**Comment by lance6716** [comment]
/hold

need add the integration test to other_integrations.txt and revert the hook of chaos

**Review by D3Hunter — APPROVED** [review]
LGTM

**Review by glorv — COMMENTED** [review]
LGTM

File: dm/relay/local_reader.go [hunk 1]
```diff
@@ -538,8 +550,11 @@ func (r *BinlogReader) parseFile(
 				state.latestPos = int64(e.Header.LogPos)
 				break
 			}
-			u, _ := uuid.FromBytes(ev.SID)
-			state.replaceWithHeartbeat, err = r.advanceCurrentGtidSet(fmt.Sprintf("%s:%d", u.String(), ev.GNO))
+			gtidStr, err2 := event.GetGTIDStr(e)
+			if err2 != nil {
+				return errors.Trace(err2)
```
Comment (GMHDBJD) [inline dm/relay/local_reader.go:555]: Seems we have abandoned trace

**Review by GMHDBJD — COMMENTED** [review]
also use lastLocation here https://github.com/pingcap/ticdc/blob/30d77eacfc74e051201b2ae46b188b158d84d6bf/dm/syncer/syncer.go#L1664 as we do in #3491

**Review by GMHDBJD — COMMENTED** [review]
rest LGTM
By the way, can we return an error in syncer after relay send ErrorMaybeDuplicateEvent, and just rely on safemode to deal with duplicate?

File: dm/relay/relay.go [hunk 2]
```diff
@@ -343,6 +347,18 @@ func (r *Relay) process(ctx context.Context) error {
...
+						res.Event.Header.EventType == replication.MARIADB_GTID_EVENT {
+						gtidStr, err3 := event.GetGTIDStr(res.Event)
+						if err3 != nil {
+							return err3
+						}
+
+						if gtidStr != r.currentGTID {
+							return errors.New("after recover GTID-based replication, the first GTID is not same as broken one")
+						}
+					}
```
Comment (GMHDBJD) [inline dm/relay/relay.go:361]: I don't think we need these extra logic(L334-L361) for duplicate events since we have deal with it in https://github.com/pingcap/ticdc/blob/0076d097b2ab252ca81b7a05430c90f34b73754d/dm/relay/relay_writer.go#L247

File: dm/relay/local_reader.go (hunk 1 above)
Comment (lance6716) [reply dm/relay/local_reader.go:555]: I remember I have seen some zap logger printing error stack 🤔

**Comment by lance6716** [comment]
> also use lastLocation here
> 
> https://github.com/pingcap/ticdc/blob/30d77eacfc74e051201b2ae46b188b158d84d6bf/dm/syncer/syncer.go#L1664
> 
> as we do in #3491

checked that in handleQueryEvent of BEGIN, we will update `lastLocation` to the GTID set of this event. so reseting to `lastLocation` will skip this transaction 😂 I hope we can refactor locations in https://github.com/pingcap/ticdc/pull/3526 and following PR.

I'll check release branch soon.

File: dm/relay/relay.go [hunk 3]
```diff
@@ -581,16 +553,16 @@ func (r *Relay) handleEvents(
 	ctx context.Context,
 	reader2 Reader,
 	parser2 *parser.Parser,
-) (int, error) {
```
Comment (Ehco1996) [inline dm/relay/relay.go:584]: please remove this comment  of this func `// the first return value is the index of last read rows event if the transaction is not finished.`

File: dm/relay/local_reader.go [hunk 4]
```diff
@@ -627,15 +645,6 @@ func (r *BinlogReader) parseFile(
 	if err != nil {
 		if state.possibleLast && isIgnorableParseError(err) {
 			r.tctx.L().Warn("fail to parse relay log file, meet some ignorable error", zap.String("file", state.fullPath), zap.Int64("offset", offset), zap.Error(err))
```
Comment (Ehco1996) [inline dm/relay/local_reader.go:647]: do we need this log now ?
maybe 
```
	if err != nil && !(state.possibleLast && isIgnorableParseError(err)) {
		r.tctx.L().Error("parse relay log file", zap.String("file", state.fullPath), zap.Int64("offset", offset), zap.Error(err))
		return false, false, terror.ErrParserParseRelayLog.Delegate(err, state.fullPath)
	}
```

**Review by Ehco1996 — COMMENTED** [review]
rest LGTM GreatJob !

**Review by lichunzhu — APPROVED** [review]

**Review by Ehco1996 — APPROVED** [review]
LGTM

**Comment by Ehco1996** [comment]
seems relay test failed is not a unstable test, it failed every time 🤔

* https://ci.pingcap.net/blue/organizations/jenkins/atom-ut/detail/atom-ut/3715/tests/
* https://ci.pingcap.net/blue/organizations/jenkins/atom-ut/detail/atom-ut/3667/tests/
* https://ci.pingcap.net/blue/organizations/jenkins/atom-ut/detail/atom-ut/3689/tests/
