### PR TITLE
mounter: handle NaN Inf in mounter

### LINKED ISSUE #781: Failed to replicate overflow float field
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

   1. setup a cdc cluster, create changefeed
   2. in upstream, execute following SQLs

      ```
      > create table t4 (id int primary key, a float);
      > insert into t4 values (1, power(2, 128));
      ```

2. What did you expect to see?

   Replication is normal.

3. What did you see instead?

```
[2020/07/20 21:26:24.421 +08:00] [ERROR] [processor.go:976] ["error on running processor"] [captureid=a83558ed-83e7-4b9f-8de0-30cc485b862e] [captureaddr=127.0.0.1:8300] [changefeedid=5bdd2985-e27f-40ab-926d-5b58e2844567] [processorid=5a5e622f-3a89-4303-8eb1-aa22a6838ea8] [error="Error 1054: Unknown column 'Inf' in 'field list'"] [errorVerbose="Error 1054: Unknown column 'Inf' in 'field list'
github.com/pingcap/errors.AddStack
        github.com/pingcap/errors@v0.11.5-0.20190809092503-95897b64e011/errors.go:174
github.com/pingcap/errors.Trace
        github.com/pingcap/errors@v0.11.5-0.20190809092503-95897b64e011/juju_adaptor.go:15
github.com/pingcap/ticdc/cdc/sink.(*mysqlSink).execDMLWithMaxRetries.func2.2
        github.com/pingcap/ticdc/cdc/sink/mysql.go:648
github.com/pingcap/ticdc/cdc/sink.(*Statistics).RecordBatchExecution
        github.com/pingcap/ticdc/cdc/sink/statistics.go:60
github.com/pingcap/ticdc/cdc/sink.(*mysqlSink).execDMLWithMaxRetries.func2
        github.com/pingcap/ticdc/cdc/sink/mysql.go:640
github.com/pingcap/ticdc/pkg/retry.Run.func1
        github.com/pingcap/ticdc/pkg/retry/retry.go:31
github.com/cenkalti/backoff.RetryNotify
        github.com/cenkalti/backoff@v2.2.1+incompatible/retry.go:37
github.com/cenkalti/backoff.Retry
        github.com/cenkalti/backoff@v2.2.1+incompatible/retry.go:24
github.com/pingcap/ticdc/pkg/retry.Run
        github.com/pingcap/ticdc/pkg/retry/retry.go:30
github.com/pingcap/ticdc/cdc/sink.(*mysqlSink).execDMLWithMaxRetries
        github.com/pingcap/ticdc/cdc/sink/mysql.go:635
github.com/pingcap/ticdc/cdc/sink.(*mysqlSink).execDMLs
        github.com/pingcap/ticdc/cdc/sink/mysql.go:703
github.com/pingcap/ticdc/cdc/sink.(*mysqlSinkWorker).run.func2
        github.com/pingcap/ticdc/cdc/sink/mysql.go:579
github.com/pingcap/ticdc/cdc/sink.(*mysqlSinkWorker).run
        github.com/pingcap/ticdc/cdc/sink/mysql.go:614
github.com/pingcap/ticdc/cdc/sink.(*mysqlSink).concurrentExec.func1
        github.com/pingcap/ticdc/cdc/sink/mysql.go:475
golang.org/x/sync/errgroup.(*Group).Go.func1
        golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57
runtime.goexit
        runtime/asm_amd64.s:1373"]
```

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        master
        ```

    - TiCDC version (execute `cdc version`):

        ```
        Release Version: v4.0.2-48-ge974657
        Git Commit Hash: e9746572e7d17e658c4d55fdb339fa51ac83fe4c
        Git Branch: master
        UTC Build Time: 2020-07-20 13:24:08
        Go Version: go version go1.14.4 linux/amd64
        ```

### PR DESCRIPTION
**Pull request by leoppro**
### What problem does this PR solve? 
fix #781

### Check List 

Tests 

 - Unit test
 - Integration test

### CODE REVIEW

File: cdc/entry/mounter.go [hunk 1]
```diff
@@ -555,6 +556,13 @@ func formatColVal(datum types.Datum, tp byte) (interface{}, error) {
 			b = emptyBytes
 		}
 		return b, nil
+	case mysql.TypeFloat, mysql.TypeDouble:
+		v := datum.GetFloat64()
+		if math.IsNaN(v) || math.IsInf(v, 1) || math.IsInf(v, -1) {
+			v = 0
+			log.Warn("the value is invalid in column", zap.Float64("value", v))
```
Comment (amyangfei) [inline cdc/entry/mounter.go:563]: Oh, seems the log doesn't help user to locate the row.
Btw we should log before `v` is set to zero

**Comment by leoppro** [comment]
@amyangfei  PTAL again

File: cdc/entry/mounter.go [hunk 2]
```diff
@@ -525,38 +534,46 @@ func (m *mounterImpl) mountIndexKVEntry(tableInfo *model.TableInfo, idx *indexKV
...
 		b := datum.GetBytes()
 		if b == nil {
 			b = emptyBytes
 		}
-		return b, nil
+		return b, "", nil
+	case mysql.TypeFloat, mysql.TypeDouble:
+		v := datum.GetFloat64()
+		if math.IsNaN(v) || math.IsInf(v, 1) || math.IsInf(v, -1) {
+			warn = fmt.Sprintf("the value is invalid in column: %f", v)
```
Comment (leoppro) [inline cdc/entry/mounter.go:571]: https://play.golang.org/p/n2h8bkK0DvV

**Review by amyangfei — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

**Comment by overvenus** [comment]
/run-integration-tests tidb=release-4.0 tikv=release-4.0 pd=release-4.0

**Comment by leoppro** [comment]
/run-integration-tests tidb=release-4.0 tikv=release-4.0 pd=release-4.0
