### PR TITLE
Fix crts maybe less than emit resolved ts in processor

### LINKED ISSUE #644: Fatal error: Commit Ts is less than Resolved Ts
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

The CI fails with a fatal error: The CRTs must be greater than the resolvedTs. It means we may mistakenly advance resolved ts, and it could cause data lose.

[fatal.log](https://github.com/pingcap/ticdc/files/4764392/fatal.log)

2. What did you expect to see?

No fatal error.

3. What did you see instead?

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        master
        ```

    - TiCDC version (execute `cdc version`):

        ```
        https://github.com/pingcap/ticdc/pull/642/
        ```

### PR DESCRIPTION
**Pull request by amyangfei**
### What problem does this PR solve? 

Fix #644 

Found two bugs:

~1. sinkEmittedResolvedTs and real emitted row changed events
    - each sorter sends row changed events to the output channel of a processor.
    - but resolved ts of each table is updated asynchronously, which means if the resolved ts of a table is updated, some row changed events before this resolved ts may be not consumed by processor yet.~ as `processor.output` chan is sequence, when resolved ts event is fetched, row changed events must have been consumed.
2. processor local resolved ts calculation and mark table (Then why the cyclic test often meets this bug makes sense )
    - processor receives and emits row changed events of mark table, but mark table is not maintained in processor table list, and when calculating processor local resolved ts, the mark table is not taken into consideration. https://github.com/pingcap/ticdc/blob/master/cdc/processor.go#L827-L833

### What is changed and how it works?

~- Update table's resolved ts and consume row changed events in the same routine in processor.~
- Maintain both normal tables and mark tables in processor.

### Check List 

Tests 

 - Integration test

Related changes

 - Need to cherry-pick to the release branch

### Release note

- No release note

### CODE REVIEW

File: cdc/processor.go [hunk 1]
```diff
@@ -109,18 +110,31 @@ type processor struct {
 }
 
 type tableInfo struct {
-	id         int64
-	resolvedTS uint64
-	workload   model.WorkloadInfo
-	cancel     context.CancelFunc
+	id          int64
+	resolvedTs  uint64
+	mid         int64
```
Comment (leoppro) [inline cdc/processor.go:115]:
```suggestion
	markTableId         int64
```

File: cdc/processor.go [hunk 2]
```diff
@@ -741,14 +754,14 @@ func (p *processor) addTable(ctx context.Context, tableID int64, replicaInfo *mo
...
-		resolvedTS: replicaInfo.StartTs,
+		resolvedTs: replicaInfo.StartTs,
 		cancel:     cancel,
 	}
 	// TODO(leoppro) calculate the workload of this table
 	// We temporarily set the value to constant 1
 	table.workload = model.WorkloadInfo{Workload: 1}
 
-	startPuller := func(tableID model.TableID) {
+	startPuller := func(tableID model.TableID, isMarkTable bool) {
```
Comment (leoppro) [inline cdc/processor.go:764]: how about this?
```suggestion
	startPuller := func(tableID model.TableID, resolvedTs *uint64) {
```
and we can remove `storeResolvedTs` function, just using `atomic.StoreUint64(resolvedTs, ts)`

Comment (leoppro) [reply cdc/processor.go:764]: we can avoid having to judge in a loop by this way

File: cdc/processor.go [hunk 3]
```diff
@@ -109,18 +109,27 @@ type processor struct {
...
+		if mTableRts < tableRts {
+			return mTableRts
+		}
+	}
+	return tableRts
 }
 
-func (t *tableInfo) storeResolvedTS(ts uint64) {
-	atomic.StoreUint64(&t.resolvedTS, ts)
+func (t *tableInfo) storeResolvedTs(ts uint64, rts *uint64) {
```
Comment (leoppro) [inline cdc/processor.go:131]: I think we can remove this function 😊

Comment (amyangfei) [reply cdc/processor.go]: fine
