### PR TITLE
*: fix data race in dynamic stream

### LINKED ISSUE #1248: Find data race in  dynamic stream
### What did you do?

run test http_api_tls

### What did you expect to see?

_No response_

### What did you see instead?

https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Fticdc%2Fpull_cdc_mysql_integration_light/detail/pull_cdc_mysql_integration_light/527/pipeline
```log
==================
WARNING: DATA RACE
Write at 0x00c001099190 by goroutine 2616:
  runtime.closechan()
      /go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.7.linux-amd64/src/runtime/chan.go:397 +0x0
  github.com/pingcap/ticdc/utils/dynstream.(*stream[go.shape.struct { Low uint64 "json:\"low\""; High uint64 "json:\"high\"" },go.shape.struct { Low uint64 "json:\"low\""; High uint64 "json:\"high\"" },go.shape.struct { From *github.com/pingcap/ticdc/pkg/node.ID; github.com/pingcap/ticdc/pkg/common/event.Event },go.shape.*uint8,go.shape.*uint8]).close()
      /home/jenkins/agent/workspace/pingcap/ticdc/pull_cdc_mysql_integration_light/ticdc/utils/dynstream/stream.go:122 +0x10a
  github.com/pingcap/ticdc/utils/dynstream.(*parallelDynamicStream[go.shape.struct { Low uint64 "json:\"low\""; High uint64 "json:\"high\"" },go.shape.struct { Low uint64 "json:\"low\""; High uint64 "json:\"high\"" },go.shape.struct { From *github.com/pingcap/ticdc/pkg/node.ID; github.com/pingcap/ticdc/pkg/common/event.Event },go.shape.*uint8,go.shape.*uint8]).Close()
      /home/jenkins/agent/workspace/pingcap/ticdc/pull_cdc_mysql_integration_light/ticdc/utils/dynstream/parallel_dynamic_stream.go:96 +0x2f5
  github.com/pingcap/ticdc/utils/dynstream.(*parallelDynamicStream[github.com/pingcap/ticdc/pkg/common.GID,github.com/pingcap/ticdc/pkg/common.DispatcherID,github.com/pingcap/ticdc/downstreamadapter/dispatcher.DispatcherEvent,*github.com/pingcap/ticdc/downstreamadapter/eventcollector.dispatcherStat,*github.com/pingcap/ticdc/downstreamadapter/eventcollector.EventsHandler]).Close()
      /home/jenkins/agent/workspace/pingcap/ticdc/pull_cdc_mysql_integration_light/ticdc/utils/dynstream/parallel_dynamic_stream.go:85 +0x36
  github.com/pingcap/ticdc/downstreamadapter/eventcollector.(*EventCollector).Close()
      /home/jenkins/agent/workspace/pingcap/ticdc/pull_cdc_mysql_integration_light/ticdc/downstreamadapter/eventcollector/event_collector.go:167 +0xe4
  github.com/pingcap/ticdc/server.(*server).closePreServices.func1.1()
      /home/jenkins/agent/workspace/pingcap/ticdc/pull_cdc_mysql_integration_light/ticdc/server/server.go:333 +0x54

Previous read at 0x00c001099190 by goroutine 2620:
  runtime.chansend()
      /go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.7.linux-amd64/src/runtime/chan.go:171 +0x0
  github.com/pingcap/ticdc/utils/dynstream.(*parallelDynamicStream[go.shape.struct { Low uint64 "json:\"low\""; High uint64 "json:\"high\"" },go.shape.struct { Low uint64 "json:\"low\""; High uint64 "json:\"high\"" },go.shape.struct { From *github.com/pingcap/ticdc/pkg/node.ID; github.com/pingcap/ticdc/pkg/common/event.Event },go.shape.*uint8,go.shape.*uint8]).RemovePath()
      /home/jenkins/agent/workspace/pingcap/ticdc/pull_cdc_mysql_integration_light/ticdc/utils/dynstream/parallel_dynamic_stream.go:185 +0x2f5
  github.com/pingcap/ticdc/utils/dynstream.(*parallelDynamicStream[github.com/pingcap/ticdc/pkg/common.GID,github.com/pingcap/ticdc/pkg/common.DispatcherID,github.com/pingcap/ticdc/downstreamadapter/dispatcher.DispatcherEvent,*github.com/pingcap/ticdc/downstreamadapter/eventcollector.dispatcherStat,*github.com/pingcap/ticdc/downstreamadapter/eventcollector.EventsHandler]).RemovePath()
      /home/jenkins/agent/workspace/pingcap/ticdc/pull_cdc_mysql_integration_light/ticdc/utils/dynstream/parallel_dynamic_stream.go:168 +0x4a
  github.com/pingcap/ticdc/downstreamadapter/eventcollector.(*EventCollector).RemoveDispatcher()
      /home/jenkins/agent/workspace/pingcap/ticdc/pull_cdc_mysql_integration_light/ticdc/downstreamadapter/eventcollector/event_collector.go:237 +0x52d
  github.com/pingcap/ticdc/downstreamadapter/dispatchermanager.(*EventDispatcherManager).closeAllDispatchers.func1()
      /home/jenkins/agent/workspace/pingcap/ticdc/pull_cdc_mysql_integration_light/ticdc/downstreamadapter/dispatchermanager/event_dispatcher_manager.go:342 +0x84
  github.com/pingcap/ticdc/downstreamadapter/dispatchermanager.(*DispatcherMap).ForEach.func1()
      /home/jenkins/agent/workspace/pingcap/ticdc/pull_cdc_mysql_integration_light/ticdc/downstreamadapter/dispatchermanager/helper.go:101 +0x95
  sync.(*Map).Range()
      /go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.7.linux-amd64/src/sync/map.go:501 +0x1e5
  github.com/pingcap/ticdc/downstreamadapter/dispatchermanager.(*DispatcherMap).ForEach()
      /home/jenkins/agent/workspace/pingcap/ticdc/pull_cdc_mysql_integration_light/ticdc/downstreamadapter/dispatchermanager/helper.go:100 +0xd3
  github.com/pingcap/ticdc/downstreamadapter/dispatchermanager.(*EventDispatcherManager).closeAllDispatchers()
      /home/jenkins/agent/workspace/pingcap/ticdc/pull_cdc_mysql_integration_light/ticdc/downstreamadapter/dispatchermanager/event_dispatcher_manager.go:340 +0x144
  github.com/pingcap/ticdc/downstreamadapter/dispatchermanager.(*EventDispatcherManager).close()
      /home/jenkins/agent/workspace/pingcap/ticdc/pull_cdc_mysql_integration_light/ticdc/downstreamadapter/dispatchermanager/event_dispatcher_manager.go:302 +0x239
  github.com/pingcap/ticdc/downstreamadapter/dispatchermanager.(*EventDispatcherManager).TryClose.gowrap1()
      /home/jenkins/agent/workspace/pingcap/ticdc/pull_cdc_mysql_integration_light/ticdc/downstreamadapter/dispatchermanager/event_dispatcher_manager.go:266 +0x44

Goroutine 2616 (running) created at:
  github.com/pingcap/ticdc/server.(*server).closePreServices.func1()
      /home/jenkins/agent/workspace/pingcap/ticdc/pull_cdc_mysql_integration_light/ticdc/server/server.go:332 +0x138
  golang.org/x/sync/errgroup.(*Group).Go.func1()
      /go/pkg/mod/golang.org/x/sync@v0.13.0/errgroup/errgroup.go:79 +0x91

Goroutine 2620 (running) created at:
  github.com/pingcap/ticdc/downstreamadapter/dispatchermanager.(*EventDispatcherManager).TryClose()
      /home/jenkins/agent/workspace/pingcap/ticdc/pull_cdc_mysql_integration_light/ticdc/downstreamadapter/dispatchermanager/event_dispatcher_manager.go:266 +0x17b
  github.com/pingcap/ticdc/downstreamadapter/dispatcherorchestrator.(*DispatcherOrchestrator).Close()
      /home/jenkins/agent/workspace/pingcap/ticdc/pull_cdc_mysql_integration_light/ticdc/downstreamadapter/dispatcherorchestrator/dispatcher_orchestrator.go:296 +0x338
  github.com/pingcap/ticdc/server.(*server).closePreServices.func1.1()
      /home/jenkins/agent/workspace/pingcap/ticdc/pull_cdc_mysql_integration_light/ticdc/server/server.go:333 +0x54
==================
```

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
```

### PR DESCRIPTION
**Pull request by wk989898**
### What problem does this PR solve?

Issue Number: close #1248

#### Tests 

- Unit test
- Integration test

### Release note 

```release-note
`None`.
```

### CODE REVIEW

File: utils/dynstream/parallel_dynamic_stream.go [hunk 1]
```diff
@@ -120,7 +120,12 @@ func (s *parallelDynamicStream[A, P, T, D, H]) Push(path P, e T) {
 		timestamp: s.handler.GetTimestamp(e),
 		queueTime: time.Now(),
 	}
+	if pi.stream.isClosed.Load() {
+		return
+	}
+	pi.stream.eventWg.Add(1)
```
Comment (flowbehappy) [inline utils/dynstream/parallel_dynamic_stream.go:126]: It is expensive for `Put`.

**Review by hongyunyan — APPROVED** [review]
