### PR TITLE
owner, errors: ignore update gc safepoint error

### LINKED ISSUE #954: Owner exits due to PD no leader during tiup cluster upgrading
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

```bash
tiup cluster upgrade <cluster-name> v4.0.6
```

```
/data1/deploy/cdc-8300/log/cdc-2020-09-14T16-07-46.647.log:719401:[2020/09/14 16:02:57.593 +08:00] [ERROR] [pd.go:130] ["updateTS error"] [error="rpc error: code = Unknown desc = can not get timestamp, may be not leader"] [errorVerbose="rpc error: code = Unknown desc = can not get timestamp, may be not leader
github.com/pingcap/pd/v4/client.(*client).processTSORequests
	github.com/pingcap/pd/v4@v4.0.5-0.20200817114353-e465cafe8a91/client/client.go:319
github.com/pingcap/pd/v4/client.(*client).tsLoop
	github.com/pingcap/pd/v4@v4.0.5-0.20200817114353-e465cafe8a91/client/client.go:268
runtime.goexit
	runtime/asm_amd64.s:1357
github.com/pingcap/pd/v4/client.(*tsoRequest).Wait
	github.com/pingcap/pd/v4@v4.0.5-0.20200817114353-e465cafe8a91/client/client.go:429
github.com/pingcap/pd/v4/client.(*client).GetTS
	github.com/pingcap/pd/v4@v4.0.5-0.20200817114353-e465cafe8a91/client/client.go:447
github.com/pingcap/tidb/store/tikv/oracle/oracles.(*pdOracle).getTimestamp
	github.com/pingcap/tidb@v1.1.0-beta.0.20200820092836-c5b7658b0896/store/tikv/oracle/oracles/pd.go:103
github.com/pingcap/tidb/store/tikv/oracle/oracles.(*pdOracle).updateTS
	github.com/pingcap/tidb@v1.1.0-beta.0.20200820092836-c5b7658b0896/store/tikv/oracle/oracles/pd.go:128
runtime.goexit
	runtime/asm_amd64.s:1357
github.com/pingcap/errors.AddStack
	github.com/pingcap/errors@v0.11.5-0.20200729012136-4e113ddee29e/errors.go:174
github.com/pingcap/errors.Trace
	github.com/pingcap/errors@v0.11.5-0.20200729012136-4e113ddee29e/juju_adaptor.go:15
github.com/pingcap/tidb/store/tikv/oracle/oracles.(*pdOracle).getTimestamp
	github.com/pingcap/tidb@v1.1.0-beta.0.20200820092836-c5b7658b0896/store/tikv/oracle/oracles/pd.go:105
github.com/pingcap/tidb/store/tikv/oracle/oracles.(*pdOracle).updateTS
	github.com/pingcap/tidb@v1.1.0-beta.0.20200820092836-c5b7658b0896/store/tikv/oracle/oracles/pd.go:128
runtime.goexit
	runtime/asm_amd64.s:1357"]

/data1/deploy/cdc-8300/log/cdc-2020-09-14T16-07-46.647.log:719403:[2020/09/14 16:02:58.090 +08:00] [ERROR] [owner.go:945] ["owner exited with error"] [error="rpc error: code = Unknown desc = rpc error: code = Unavailable desc = not leader"] [errorVerbose="rpc error: code = Unknown desc = rpc error: code = Unavailable desc = not leader
github.com/pingcap/pd/v4/client.(*client).UpdateServiceGCSafePoint
	github.com/pingcap/pd/v4@v4.0.5-0.20200817114353-e465cafe8a91/client/client.go:672
github.com/pingcap/ticdc/cdc.(*Owner).flushChangeFeedInfos
	github.com/pingcap/ticdc@/cdc/owner.go:582
github.com/pingcap/ticdc/cdc.(*Owner).run
	github.com/pingcap/ticdc@/cdc/owner.go:1015
github.com/pingcap/ticdc/cdc.(*Owner).Run
	github.com/pingcap/ticdc@/cdc/owner.go:942
github.com/pingcap/ticdc/cdc.(*Server).campaignOwnerLoop
	github.com/pingcap/ticdc@/cdc/server.go:266
github.com/pingcap/ticdc/cdc.(*Server).run.func1
	github.com/pingcap/ticdc@/cdc/server.go:297
golang.org/x/sync/errgroup.(*Group).Go.func1
	golang.org/x/sync@v0.0.0-20200625203802-6e8e738ad208/errgroup/errgroup.go:57
runtime.goexit
	runtime/asm_amd64.s:1357
github.com/pingcap/errors.AddStack
	github.com/pingcap/errors@v0.11.5-0.20200729012136-4e113ddee29e/errors.go:174
github.com/pingcap/errors.Trace
	github.com/pingcap/errors@v0.11.5-0.20200729012136-4e113ddee29e/juju_adaptor.go:15
github.com/pingcap/ticdc/cdc.(*Owner).flushChangeFeedInfos
	github.com/pingcap/ticdc@/cdc/owner.go:585
github.com/pingcap/ticdc/cdc.(*Owner).run
	github.com/pingcap/ticdc@/cdc/owner.go:1015
github.com/pingcap/ticdc/cdc.(*Owner).Run
	github.com/pingcap/ticdc@/cdc/owner.go:942
github.com/pingcap/ticdc/cdc.(*Server).campaignOwnerLoop
	github.com/pingcap/ticdc@/cdc/server.go:266
github.com/pingcap/ticdc/cdc.(*Server).run.func1
	github.com/pingcap/ticdc@/cdc/server.go:297
golang.org/x/sync/errgroup.(*Group).Go.func1
	golang.org/x/sync@v0.0.0-20200625203802-6e8e738ad208/errgroup/errgroup.go:57
runtime.goexit
	runtime/asm_amd64.s:1357"]
```

2. What did you expect to see?

owner does not exit.

3. What did you see instead?

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        v4.0.5
        ```

    - TiCDC version (execute `cdc version`):

        ```
        v4.0.5
        ```

### PR DESCRIPTION
**Pull request by overvenus**
### What problem does this PR solve? 

Fix #954 

### What is changed and how it works?

Ignore update gc safepoint error

### Check List 

Tests 

 - Unit test

Related changes

 - Need to cherry-pick to the release branch

### Release note

- Fix unexpected exit due to updating GC safepoint error.

### CODE REVIEW

**Comment by overvenus** [comment]
PTAL

File: cdc/owner_test.go [hunk 1]
```diff
@@ -74,6 +76,25 @@ func (s *ownerSuite) TearDownTest(c *check.C) {
...
+
+func (s *ownerSuite) TestOwnerFlushChangeFeedInfos(c *check.C) {
+	mockOwner := Owner{
+		pdClient:              &mockPDClient{},
+		gcSafepointLastUpdate: time.Now(),
+	}
+
+	// Owner should ignore UpdateServiceGCSafePoint error.
+	err := mockOwner.flushChangeFeedInfos(s.ctx)
+	c.Assert(err, check.IsNil)
```
Comment (amyangfei) [inline cdc/owner_test.go:95]: Recommend adding the check that `mockOwner.gcSafepointLastUpdate` is not updated

**Review by amyangfei — COMMENTED** [review]
LGTM

**Review by leoppro — APPROVED** [review]

**Review by ti-srebot — APPROVED** [review]
