### PR TITLE
kvclient: filter the old value if old-value is disabled

### LINKED ISSUE #1299: old value feature can't be turned off if changefeed has enabled it
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

    ```
    1. create two changefeed with `enable-old-value=true`, and replicate with a same table
    2. pause one of the changefeed (changefeed-1)
    3. update changefeed-1, set `enable old value = false`
    4. resume changefeed-1, the output result from changefeed-1 still contain old-value column
    ```

2. What did you expect to see?

   `old-value` feature can be turned off

3. What did you see instead?

   `old-value` feature can't be turned off

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        v4.0.9
        ```

    - TiCDC version (execute `cdc version`):

        ```
        v4.0.9
        ```
5. Others

  - We need to confirm when multiple changefeeds exist, whether changefeed with old-value enabled will affect changefeed with old-value turned off.

there is another way to reproduce the error:
```
    1. create a changefeed to listen table1 with `enable-old-value=true`
    2. create another changefeed to listen the same table1 with `enable-old-value=false`
```

we can see that all of changefeed will output the row changed event with old value

### PR DESCRIPTION
**Pull request by leoppro**
### What problem does this PR solve? 
fix #1299 

### What is changed and how it works?

set `Oldvalue` to `nil` when `old-value` is disabled

### Check List 

Tests 

 - Unit test
 - Integration test

### Release note

- Fix the old-value switch of a changefeed could be affected by another changefeed

### CODE REVIEW

**Review by amyangfei — COMMENTED** [review]
Recommend adding an integration test

File: cdc/kv/matcher.go [hunk 1]
```diff
@@ -39,39 +36,60 @@ func newMatchKey(row *cdcpb.Event_Row) matchKey {
...
 	}
-	m.unmatchedValue[key] = &pendingValue{
-		value:    value,
-		oldValue: oldvalue,
-	}
+	m.unmatchedValue[key] = row
 }
 
-func (m *matcher) matchRow(row *cdcpb.Event_Row) (*pendingValue, bool) {
+func (m *matcher) matchRow(row *cdcpb.Event_Row) bool {
```
Comment (amyangfei) [inline cdc/kv/matcher.go:59]: Please add a comment that the `Value` and `OldValue` will be assigned if a matched prewrite event exists.

File: cdc/kv/client.go [hunk 2]
```diff
@@ -1462,7 +1433,7 @@ func (s *eventFeedSession) singleEventFeed(
 								zap.Uint64("regionID", regionID))
 						}
 						// emit a value
```
Comment (amyangfei) [inline cdc/kv/client.go:1435]:
```suggestion
```

File: cdc/kv/matcher.go [hunk 3]
```diff
@@ -39,39 +36,60 @@ func newMatchKey(row *cdcpb.Event_Row) matchKey {
...
+	return false
 }
 
 func (m *matcher) cacheCommitRow(row *cdcpb.Event_Row) {
 	m.cachedCommit = append(m.cachedCommit, row)
 }
 
-func (m *matcher) clearCacheCommit() {
+func (m *matcher) matchCachedRow() []*cdcpb.Event_Row {
+	cachedCommit := m.cachedCommit
```
Comment (amyangfei) [inline cdc/kv/matcher.go:74]: `m.cachedCommit` could be appended data only before `initialized`, and consume once after `initialized`. Seems we can filter matched row on `m.cacheCommit` inplace.

File: cdc/kv/client.go [hunk 4]
```diff
@@ -1410,30 +1400,11 @@ func (s *eventFeedSession) singleEventFeed(
 								return lastResolvedTs, errors.Trace(ctx.Err())
 							}
 						}
-						matcher.clearCacheCommit()
```
Comment (amyangfei) [inline cdc/kv/client.go:1413]: Why is this removed

File: errors.toml [hunk 5]
```diff
@@ -1,5 +1,5 @@
-# AUTOGENERATED BY github.com/pingcap/errors/errdoc-gen
-# YOU CAN CHANGE THE 'description'/'workaround' FIELDS IF THEM ARE IMPROPER.
+# AUTOGENERATED BY github.com/pingcap/tiup/components/errdoc/errdoc-gen
```
Comment (overvenus) [inline errors.toml:1]: Please update your errdoc-gen.

Comment (leoppro) [reply errors.toml:1]: fixed

**Review by amyangfei — COMMENTED** [review]
LGTM

**Comment by overvenus** [comment]
Could you add some old value integration tests?

**Comment by leoppro** [comment]
> Could you add some old value integration tests?

what kind of old-value tests?

**Comment by overvenus** [comment]
An end to end test, multiple changefeeds with different old-value setting, we need make sure they do not interfere each other.

File: tests/multi_changefeed/run.sh [hunk 6]
```diff
@@ -0,0 +1,69 @@
...
+    cdc cli changefeed create --pd=$pd_addr --sink-uri="$SINK_URI" -c "old-value-cf" --config="$CUR/conf/changefeed1.toml"
+    cdc cli changefeed create --pd=$pd_addr --sink-uri="$SINK_URI" -c "no-old-value-cf" --config="$CUR/conf/changefeed2.toml"
+
+    run_sql "CREATE DATABASE multi_changefeed;" ${UP_TIDB_HOST} ${UP_TIDB_PORT}
+    run_sql "CREATE table multi_changefeed.t1 (id int primary key, val int);" ${UP_TIDB_HOST} ${UP_TIDB_PORT}
+    run_sql "INSERT INTO multi_changefeed.t1 VALUES (1,1);" ${UP_TIDB_HOST} ${UP_TIDB_PORT}
+    run_sql "UPDATE multi_changefeed.t1 SET val = 2;" ${UP_TIDB_HOST} ${UP_TIDB_PORT}
+    run_sql "DELETE FROM multi_changefeed.t1;" ${UP_TIDB_HOST} ${UP_TIDB_PORT}
+
+    grep "BlockHoleSink: FlushRowChangedEvents" $WORK_DIR/cdc.log
```
Comment (leoppro) [inline tests/multi_changefeed/run.sh:61]:
```suggestion
    echo "a"
    grep "BlockHoleSink: FlushRowChangedEvents" $WORK_DIR/cdc.log > $WORK_DIR/output.log
    echo "b"
```

File: tests/multi_changefeed/run.sh [hunk 7]
```diff
@@ -0,0 +1,69 @@
...
+    start_tidb_cluster --workdir $WORK_DIR
+    cd $WORK_DIR
+
+    pd_addr="http://$UP_PD_HOST_1:$UP_PD_PORT_1"
+    SINK_URI="blackhole://"
+
+    run_cdc_server --workdir $WORK_DIR --binary $CDC_BINARY --addr "127.0.0.1:8300" --pd $pd_addr
+    cdc cli changefeed create --pd=$pd_addr --sink-uri="$SINK_URI" -c "old-value-cf" --config="$CUR/conf/changefeed1.toml"
+    cdc cli changefeed create --pd=$pd_addr --sink-uri="$SINK_URI" -c "no-old-value-cf" --config="$CUR/conf/changefeed2.toml"
+
```
Comment (leoppro) [inline tests/multi_changefeed/run.sh:54]:
```suggestion
    echo "c"
```

File: tests/multi_changefeed/run.sh [hunk 8]
```diff
@@ -0,0 +1,71 @@
...
+    cdc cli changefeed create --pd=$pd_addr --sink-uri="$SINK_URI" -c "old-value-cf" --config="$CUR/conf/changefeed1.toml"
+    cdc cli changefeed create --pd=$pd_addr --sink-uri="$SINK_URI" -c "no-old-value-cf" --config="$CUR/conf/changefeed2.toml"
+    echo "c"
+    run_sql "CREATE DATABASE multi_changefeed;" ${UP_TIDB_HOST} ${UP_TIDB_PORT}
+    run_sql "CREATE table multi_changefeed.t1 (id int primary key, val int);" ${UP_TIDB_HOST} ${UP_TIDB_PORT}
+    run_sql "INSERT INTO multi_changefeed.t1 VALUES (1,1);" ${UP_TIDB_HOST} ${UP_TIDB_PORT}
+    run_sql "UPDATE multi_changefeed.t1 SET val = 2;" ${UP_TIDB_HOST} ${UP_TIDB_PORT}
+    run_sql "DELETE FROM multi_changefeed.t1;" ${UP_TIDB_HOST} ${UP_TIDB_PORT}
+
+    echo "a"
```
Comment (leoppro) [inline tests/multi_changefeed/run.sh:61]:
```suggestion
    echo "a"
    ls -l $WORK_DIR
```

File: tests/multi_changefeed/run.sh [hunk 9]
```diff
@@ -0,0 +1,72 @@
...
+    ls -l $WORK_DIR
+    grep "BlockHoleSink: FlushRowChangedEvents" $WORK_DIR/cdc.log > $WORK_DIR/output.log
```
Comment (leoppro) [inline tests/multi_changefeed/run.sh:63]:
```suggestion
    grep "EmitRowChangedEvents" $WORK_DIR/cdc.log
```

**Comment by liuzix** [comment]
LGTM

**Review by ti-srebot — APPROVED** [review]

File: tests/multi_changefeed/run.sh [hunk 10]
```diff
@@ -0,0 +1,57 @@
...
+    start_tidb_cluster --workdir $WORK_DIR
+    cd $WORK_DIR
+
+    pd_addr="http://$UP_PD_HOST_1:$UP_PD_PORT_1"
+    SINK_URI="blackhole://"
+
+    run_cdc_server --workdir $WORK_DIR --binary $CDC_BINARY --addr "127.0.0.1:8300" --pd $pd_addr
+    cdc cli changefeed create --pd=$pd_addr --sink-uri="$SINK_URI" -c "old-value-cf" --config="$CUR/conf/changefeed1.toml"
+    cdc cli changefeed create --pd=$pd_addr --sink-uri="$SINK_URI" -c "no-old-value-cf" --config="$CUR/conf/changefeed2.toml"
+    echo "c"
```
Comment (leoppro) [inline tests/multi_changefeed/run.sh:44]:
```suggestion
```
