### PR TITLE
owner(ticdc): asynchronously create sink

### LINKED ISSUE #3352: TiCDC owner gets stuck when creating new kafka producer
### What did you do?

1. Setup a ticdc cluster, replicating data to Kafka
2. Sending `pause changefeed` or `remove changefeed` doesn't work

### What did you expect to see?

_No response_

### What did you see instead?

owner gets stuck

image

ticdc goroutins: 

[goroutines_222.log](https://github.com/pingcap/ticdc/files/7504106/goroutines_222.log)
[goroutines_222_second.log](https://github.com/pingcap/ticdc/files/7504107/goroutines_222_second.log)

ticdc log:

[cdc.log](https://github.com/pingcap/ticdc/files/7504189/cdc.log)

metrics: 
[metrics.tar.gz](https://github.com/pingcap/ticdc/files/7504122/metrics.tar.gz)

Two owner `newChangeFeed`, looks like some dead lock.

```
goroutine 1300 [semacquire]:
sync.runtime_SemacquireMutex(0xc00957a3d4, 0x0, 0x1)
	runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc00957a3d0)
	sync/mutex.go:138 +0xfc
sync.(*Mutex).Lock(...)
	sync/mutex.go:81
github.com/Shopify/sarama.(*Broker).send(0xc00957a380, 0x32d75c0, 0xc005f18bd0, 0xc301, 0x0, 0x0, 0x0)
	github.com/Shopify/sarama@v1.27.2/broker.go:716 +0x6e2
github.com/Shopify/sarama.(*Broker).sendAndReceive(0xc00957a380, 0x32d75c0, 0xc005f18bd0, 0x32d7620, 0xc0058157c0, 0x2942400, 0x1)
	github.com/Shopify/sarama@v1.27.2/broker.go:765 +0x84
github.com/Shopify/sarama.(*Broker).GetMetadata(0xc00957a380, 0xc005f18bd0, 0x0, 0x0, 0x1)
	github.com/Shopify/sarama@v1.27.2/broker.go:283 +0x70
github.com/Shopify/sarama.(*client).tryRefreshMetadata(0xc0093b42d0, 0x0, 0x0, 0x0, 0x64, 0x0, 0x0, 0x0, 0x22cd430, 0x0)
	github.com/Shopify/sarama@v1.27.2/client.go:880 +0x4d1
github.com/Shopify/sarama.(*client).tryRefreshMetadata.func2(0x3249ba0, 0xc000c5c3b0, 0x1, 0x1)
	github.com/Shopify/sarama@v1.27.2/client.go:859 +0x1d5
github.com/Shopify/sarama.(*client).tryRefreshMetadata(0xc0093b42d0, 0x0, 0x0, 0x0, 0x65, 0x0, 0x0, 0x0, 0x22cd430, 0x0)
	github.com/Shopify/sarama@v1.27.2/client.go:927 +0xc51
....
github.com/Shopify/sarama.(*client).tryRefreshMetadata(0xc0093b42d0, 0x0, 0x0, 0x0, 0x77, 0x0, 0x0, 0x0, 0x22cd430, 0x0)
	github.com/Shopify/sarama@v1.27.2/client.go:927 +0xc51
github.com/Shopify/sarama.(*client).tryRefreshMetadata.func2(0x3249ba0, 0xc000c5c3b0, 0x1, 0x1)
	github.com/Shopify/sarama@v1.27.2/client.go:859 +0x1d5
github.com/Shopify/sarama.(*client).tryRefreshMetadata(0xc0093b42d0, 0x0, 0x0, 0x0, 0x78, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/Shopify/sarama@v1.27.2/client.go:927 +0xc51
github.com/Shopify/sarama.(*client).RefreshMetadata(0xc0093b42d0, 0x0, 0x0, 0x0, 0x7f2b94f9d62c, 0x12)
	github.com/Shopify/sarama@v1.27.2/client.go:473 +0xbe
github.com/Shopify/sarama.NewClient(0xc0022aa750, 0x3, 0x3, 0xc0092d7c00, 0x2ad5040, 0x2, 0x3, 0xc0022aa750)
	github.com/Shopify/sarama@v1.27.2/client.go:167 +0x331
github.com/Shopify/sarama.NewAsyncProducer(0xc0022aa750, 0x3, 0x3, 0xc0092d7c00, 0x0, 0x2, 0xc0022aa750, 0x3)
	github.com/Shopify/sarama@v1.27.2/async_producer.go:126 +0x4d
github.com/pingcap/ticdc/cdc/sink/producer/kafka.NewKafkaSaramaProducer(0x32b7e80, 0xc004b6e7c0, 0xc000242b08, 0x38, 0xc000242b41, 0x15, 0x100000000, 0xc000242b65, 0x5, 0x4000000, ...)
	github.com/pingcap/ticdc@/cdc/sink/producer/kafka/kafka.go:328 +0x35a
github.com/pingcap/ticdc/cdc/sink.newKafkaSaramaSink(0x32b7e80, 0xc004b6e7c0, 0xc004876480, 0xc005165720, 0xc005d31b30, 0xc005d31b00, 0xc0093b0540, 0xc000c6a388, 0x0, 0xc000c6a340)
	github.com/pingcap/ticdc@/cdc/sink/mq.go:475 +0x44b
github.com/pingcap/ticdc/cdc/sink.init.1.func3(0x32b7e80, 0xc004b6e7c0, 0xc005ff39fa, 0xc, 0xc004876480, 0xc005165720, 0xc005d31b30, 0xc005d31b00, 0xc0093b0540, 0x27fe8e0, ...)
	github.com/pingcap/ticdc@/cdc/sink/sink.go:81 +0x7a
github.com/pingcap/ticdc/cdc/sink.NewSink(0x32b7e80, 0xc004b6e7c0, 0xc005ff39fa, 0xc, 0xc000242b00, 0xae, 0xc005165720, 0xc005d31b30, 0xc005d31b00, 0xc0093b0540, ...)
	github.com/pingcap/ticdc@/cdc/sink/sink.go:113 +0x1ef
github.com/pingcap/ticdc/cdc.(*Owner).newChangeFeed(0xc0039f2140, 0x32b7e80, 0xc004b6e7c0, 0xc005ff39fa, 0xc, 0xc005585bc0, 0xc005d31ad0, 0xc00463a300, 0x5f4063fe7d00000, 0x0, ...)
	github.com/pingcap/ticdc@/cdc/owner.go:414 +0x21bb
github.com/pingcap/ticdc/cdc.(*Owner).loadChangeFeeds(0xc0039f2140, 0x32b7e80, 0xc0054b6800, 0x0, 0x0)
	github.com/pingcap/ticdc@/cdc/owner.go:615 +0xe1c
github.com/pingcap/ticdc/cdc.(*Owner).run(0xc0039f2140, 0x32b7e80, 0xc0054b6800, 0x0, 0x0)
	github.com/pingcap/ticdc@/cdc/owner.go:1309 +0xe8
github.com/pingcap/ticdc/cdc.(*Owner).Run(0xc0039f2140, 0x32b7e80, 0xc0056960c0, 0x1dcd6500, 0x0, 0x0)
	github.com/pingcap/ticdc@/cdc/owner.go:1204 +0x3af
github.com/pingcap/ticdc/cdc.(*Server).campaignOwnerLoop(0xc000c8e660, 0x32b7e80, 0xc0056960c0, 0xc004936e40, 0x16b5000000000008)
	github.com/pingcap/ticdc@/cdc/server.go:172 +0x540
github.com/pingcap/ticdc/cdc.(*Server).run.func1(0xc000500f68, 0xc004d08240)
	github.com/pingcap/ticdc@/cdc/server.go:255 +0x3c
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc005435d40, 0xc002f0c500)
	golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:57 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:54 +0x66
```

```
goroutine 227 [semacquire]:
sync.runtime_SemacquireMutex(0xc003de2054, 0x0, 0x1)
	runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc003de2050)
	sync/mutex.go:138 +0xfc
sync.(*Mutex).Lock(...)
	sync/mutex.go:81
github.com/Shopify/sarama.(*Broker).send(0xc003de2000, 0x32d75c0, 0xc0043b9080, 0xc301, 0x0, 0x0, 0x0)
	github.com/Shopify/sarama@v1.27.2/broker.go:716 +0x6e2
github.com/Shopify/sarama.(*Broker).sendAndReceive(0xc003de2000, 0x32d75c0, 0xc0043b9080, 0x32d7620, 0xc0045f7590, 0x2942400, 0x1)
	github.com/Shopify/sarama@v1.27.2/broker.go:765 +0x84
github.com/Shopify/sarama.(*Broker).GetMetadata(0xc003de2000, 0xc0043b9080, 0x0, 0x0, 0x1)
	github.com/Shopify/sarama@v1.27.2/broker.go:283 +0x70
github.com/Shopify/sarama.(*client).tryRefreshMetadata(0xc002e81b00, 0x0, 0x0, 0x0, 0x5f, 0x0, 0x0, 0x0, 0x22cd430, 0x0)
	github.com/Shopify/sarama@v1.27.2/client.go:880 +0x4d1
...
github.com/Shopify/sarama.(*client).RefreshMetadata(0xc002e81b00, 0x0, 0x0, 0x0, 0x7f2b94f9d02c, 0x12)
	github.com/Shopify/sarama@v1.27.2/client.go:473 +0xbe
github.com/Shopify/sarama.NewClient(0xc00387ebd0, 0x3, 0x3, 0xc003007880, 0x2ad5040, 0x2, 0x3, 0xc00387ebd0)
	github.com/Shopify/sarama@v1.27.2/client.go:167 +0x331
github.com/Shopify/sarama.NewAsyncProducer(0xc00387ebd0, 0x3, 0x3, 0xc003007880, 0x0, 0x2, 0xc00387ebd0, 0x3)
	github.com/Shopify/sarama@v1.27.2/async_producer.go:126 +0x4d
github.com/pingcap/ticdc/cdc/sink/producer/kafka.NewKafkaSaramaProducer(0x32b7e80, 0xc000e7ebc0, 0xc000242638, 0x38, 0xc000242671, 0x15, 0x100000000, 0xc000242695, 0x5, 0x4000000, ...)
	github.com/pingcap/ticdc@/cdc/sink/producer/kafka/kafka.go:328 +0x35a
github.com/pingcap/ticdc/cdc/sink.newKafkaSaramaSink(0x32b7e80, 0xc000e7ebc0, 0xc0013fcc00, 0xc000818be0, 0xc000c550e0, 0xc000c54e10, 0xc003883bc0, 0xc000c6a388, 0x0, 0xc000c6a340)
	github.com/pingcap/ticdc@/cdc/sink/mq.go:475 +0x44b
github.com/pingcap/ticdc/cdc/sink.init.1.func3(0x32b7e80, 0xc000e7ebc0, 0xc00016e8ba, 0xc, 0xc0013fcc00, 0xc000818be0, 0xc000c550e0, 0xc000c54e10, 0xc003883bc0, 0x27fe8e0, ...)
	github.com/pingcap/ticdc@/cdc/sink/sink.go:81 +0x7a
github.com/pingcap/ticdc/cdc/sink.NewSink(0x32b7e80, 0xc000e7ebc0, 0xc00016e8ba, 0xc, 0xc000242630, 0xae, 0xc000818be0, 0xc000c550e0, 0xc000c54e10, 0xc003883bc0, ...)
	github.com/pingcap/ticdc@/cdc/sink/sink.go:113 +0x1ef
github.com/pingcap/ticdc/cdc.(*Owner).newChangeFeed(0xc0006783c0, 0x32b7e80, 0xc000e7ebc0, 0xc00016e8ba, 0xc, 0xc0008790b0, 0xc000879860, 0xc0012d6180, 0x5f4063fe7d00000, 0x0, ...)
	github.com/pingcap/ticdc@/cdc/owner.go:414 +0x21bb
github.com/pingcap/ticdc/cdc.(*Owner).loadChangeFeeds(0xc0006783c0, 0x32b7f40, 0xc000d9d7a0, 0x0, 0x0)
	github.com/pingcap/ticdc@/cdc/owner.go:615 +0xe1c
github.com/pingcap/ticdc/cdc.(*Owner).watchCapture(0xc0006783c0, 0x32b7e80, 0xc0004087c0, 0x1, 0x0)
	github.com/pingcap/ticdc@/cdc/owner.go:1497 +0xdc
github.com/pingcap/ticdc/cdc.(*Owner).startCaptureWatcher.func1(0x32b7e80, 0xc0004087c0, 0xc0006783c0)
	github.com/pingcap/ticdc@/cdc/owner.go:1609 +0xd2
created by github.com/pingcap/ticdc/cdc.(*Owner).startCaptureWatcher
	github.com/pingcap/ticdc@/cdc/owner.go:1598 +0x7d
```

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

TiCDC version (execute `cdc version`):

v5.0.1

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### What problem does this PR solve? 

close #3352 

### What is changed and how it works?

* rename `AsyncSink` to `DDLSink`. We should care more about the usage when naming variables, but not the way how it works.
* separate the initialization and running logic of the `DDLSink`

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)

Code changes

Side effects

Related changes

### Release note 

```release-note
fix owner may be blocked when initializing the changefeed.
```

### CODE REVIEW

File: cdc/owner/async_sink.go [hunk 1]
```diff
@@ -46,82 +47,99 @@ type AsyncSink interface {
 	// the DDL event will be sent to another goroutine and execute to downstream
 	// the caller of this function can call again and again until a true returned
 	EmitDDLEvent(ctx cdcContext.Context, ddl *model.DDLEvent) (bool, error)
-	SinkSyncpoint(ctx cdcContext.Context, checkpointTs uint64) error
+	SinkSyncPoint(ctx cdcContext.Context, checkpointTs uint64) error
```
Comment (overvenus) [inline cdc/owner/async_sink.go:50]: Could you rename it `EmitSyncPoint`? (since you touch this line)

File: cdc/owner/async_sink.go [hunk 2]
```diff
@@ -46,82 +47,99 @@ type AsyncSink interface {
...
 	var lastCheckpointTs model.Ts
 	for {
 		select {
 		case <-ctx.Done():
-			return
+			return nil
 		case err := <-s.errCh:
-			ctx.Throw(err)
-			return
+			return err
```
Comment (overvenus) [inline cdc/owner/async_sink.go:134]:
```suggestion
			return errors.Trace(err)
```

Also, could you add some comments to explain why not throw error?

Comment (3AceShowHand) [reply cdc/owner/async_sink.go:134]: since it's thrown at the outside.

File: cdc/owner/async_sink.go [hunk 3]
```diff
@@ -38,6 +37,8 @@ const (
 // The EmitCheckpointTs and EmitDDLEvent is asynchronous function for now
 // Other functions are still synchronization
 type AsyncSink interface {
```
Comment (hi-rustin) [inline cdc/owner/async_sink.go:39]: It seems unnecessary for us to expose this interface and its methods publicly.

**Review by hi-rustin — COMMENTED** [review]
rest LGTM

Do we need to consider an upper limit on the number of retries? What happens if it keeps failing?

**Review by overvenus — COMMENTED** [review]
Could you test creating sink will not blocking owner?

**Comment by 3AceShowHand** [comment]
> Could you test creating sink will not blocking owner?

It's manually tested, We can try to add an integration test for such case.

File: cdc/owner/async_sink.go [hunk 4]
```diff
@@ -34,10 +33,12 @@ const (
...
 )
 
-// AsyncSink is an async sink design for owner
+// asyncSink is an async sink design for owner
 // The EmitCheckpointTs and EmitDDLEvent is asynchronous function for now
 // Other functions are still synchronization
-type AsyncSink interface {
+type asyncSink interface {
+	// Run the asyncSink
+	Run(ctx cdcContext.Context) error
```
Comment (hi-rustin) [inline cdc/owner/async_sink.go:41]: These methods also do not seem to be necessary to expose?

Comment (3AceShowHand) [reply cdc/owner/async_sink.go]: In the codebase, the visibility of data items is quite chaotic. Maybe this needs to be addressed in a proper way.

Comment (hi-rustin) [reply cdc/owner/async_sink.go]: I think we can just keep the principle of minimal access. It will help us to find dead code.

File: cdc/owner/async_sink.go [hunk 5]
```diff
@@ -46,82 +47,99 @@ type AsyncSink interface {
 	// the DDL event will be sent to another goroutine and execute to downstream
 	// the caller of this function can call again and again until a true returned
 	EmitDDLEvent(ctx cdcContext.Context, ddl *model.DDLEvent) (bool, error)
```
Comment (hi-rustin) [inline cdc/owner/async_sink.go:49]: These methods below are the same :(

File: cdc/owner/async_sink.go [hunk 6]
```diff
@@ -46,82 +47,99 @@ type AsyncSink interface {
...
-	ddlCh         chan *model.DDLEvent
+	checkpointTs  model.Ts
 	ddlFinishedTs model.Ts
 	ddlSentTs     model.Ts
 
+	ddlCh chan *model.DDLEvent
+	errCh chan error
+
+	sink            sink.Sink
+	sinkInitHandler asyncSinkInitHandler
```
Comment (asddongmen) [inline cdc/owner/async_sink.go:66]: Could you please add a comment to indicate that the purpose of this field is to facilitate unit testing.

File: cdc/owner/async_sink.go [hunk 7]
```diff
@@ -46,82 +47,99 @@ type AsyncSink interface {
...
+		ddlCh:           make(chan *model.DDLEvent, 1),
+		errCh:           make(chan error, defaultErrChSize),
+		sinkInitHandler: asyncSinkInitializer,
+		cancel:          func() {},
+	}
+}
+
+type asyncSinkInitHandler func(ctx cdcContext.Context, a *asyncSinkImpl) error
+
+func asyncSinkInitializer(ctx cdcContext.Context, a *asyncSinkImpl) error {
```
Comment (asddongmen) [inline cdc/owner/async_sink.go:82]: May be it is better to take the required variables out of ctx and pass them in through parameters, and make ctx only use for cancel.

File: cdc/owner/async_sink.go [hunk 8]
```diff
@@ -46,82 +47,99 @@ type AsyncSink interface {
...
+
+	if err := a.syncPointStore.CreateSynctable(ctx); err != nil {
+		return errors.Trace(err)
+	}
+	return nil
 }
 
-func (s *asyncSinkImpl) run(ctx cdcContext.Context) {
-	defer s.wg.Done()
+func (s *asyncSinkImpl) run(ctx cdcContext.Context) error {
```
Comment (asddongmen) [inline cdc/owner/async_sink.go:114]: ditto

File: cdc/owner/async_sink.go [hunk 9]
```diff
@@ -34,94 +33,109 @@ const (
...
 
+	ddlCh chan *model.DDLEvent
+	errCh chan error
+
+	sink sink.Sink
+	// `sinkInitHandler` can be helpful in unit testing.
+	sinkInitHandler asyncSinkInitHandler
+
 	cancel context.CancelFunc
-	wg     sync.WaitGroup
```
Comment (hi-rustin) [inline cdc/owner/async_sink.go:66]: We should leave it unchanged, it encapsulates asynchronicity very well.

File: cdc/owner/async_sink_test.go [hunk 10]
```diff
@@ -95,88 +108,112 @@ func (s *asyncSinkSuite) TestCheckpoint(c *check.C) {
...
+	go func() {
+		defer wg.Done()
+		errCh <- asyncSink.run(ctx, ctx.ChangefeedVars().ID, ctx.ChangefeedVars().Info)
+	}()
+
+	go func() {
+		wg.Wait()
+		asyncSink.close(ctx)
+		c.Assert(<-errCh, check.IsNil)
+	}()
```
Comment (overvenus) [inline cdc/owner/async_sink_test.go:137]: Should we wait the goroutine? Will it cause leak test fail?

File: cdc/owner/async_sink_test.go [hunk 11]
```diff
@@ -95,88 +108,112 @@ func (s *asyncSinkSuite) TestCheckpoint(c *check.C) {
...
+		err := asyncSink.run(ctx, ctx.ChangefeedVars().ID, ctx.ChangefeedVars().Info)
+		if err != nil {
+			writeResultErr(err)
+		}
+	}()
+
+	go func() {
+		wg.Wait()
+		asyncSink.close(ctx)
+	}()
```
Comment (overvenus) [inline cdc/owner/async_sink_test.go:193]: Should we wait the goroutine? Will it cause leak test fail?

File: cdc/owner/feed_state_manager.go [hunk 12]
```diff
@@ -42,8 +42,10 @@ func (m *feedStateManager) Tick(state *orchestrator.ChangefeedReactorState) {
 	m.shouldBeRunning = true
 	defer func() {
 		if m.shouldBeRunning {
+			log.Info("admin job should be running")
```
[the remark this answers is not in the document]
Comment (3AceShowHand) [reply cdc/owner/feed_state_manager.go:45]: this log will be removed.

We can add more log into `patchAny` method to get more concrete information about etcd related operations.

File: cdc/owner/async_sink.go (hunk 9 above)
Comment (hi-rustin) [reply cdc/owner/async_sink.go:66]: cc: @3AceShowHand PTAL~

Comment (asddongmen) [reply cdc/owner/async_sink.go:66]: I agreed with rustin.

**Review by overvenus — APPROVED** [review]
LGTM

File: cdc/owner/async_sink.go (hunk 9 above)
Comment (3AceShowHand) [reply cdc/owner/async_sink.go:66]: I would prefer to rename it `DDLSink`.

**Review by amyangfei — APPROVED** [review]

**Comment by hi-rustin** [comment]
/hold

block by https://github.com/pingcap/ticdc/pull/3598#discussion_r768498810

I don't think renaming essentially solves the problem. It still exposes an unnecessary wg. It still essentially needs to be asynchronous, which exposes the asynchrony to the caller.

File: cdc/owner/ddl_sink.go [hunk 13]
```diff
@@ -0,0 +1,203 @@
...
+		return true, nil
+	}
+	if ddl.CommitTs <= s.ddlSentTs {
+		// the DDL event is executing and not finished yes, return false
+		return false, nil
+	}
+	select {
+	case <-ctx.Done():
+		return false, errors.Trace(ctx.Err())
+	case s.ddlCh <- ddl:
```
Comment (liuzix) [inline cdc/owner/ddl_sink.go:179]: Can you add a default branch and return false when `s.ddlCh` is blocked?

File: cdc/owner/ddl_sink.go [hunk 14]
```diff
@@ -0,0 +1,205 @@
...
+		// the DDL event is executing and not finished yet, return false
+		return false, nil
+	}
+	select {
+	case <-ctx.Done():
+		return false, errors.Trace(ctx.Err())
+	case s.ddlCh <- ddl:
+		s.ddlSentTs = ddl.CommitTs
+	default:
+		// if this hit, we can think that ddlCh is full, just return false and send the ddl in the next round.
```
Comment (overvenus) [inline cdc/owner/ddl_sink.go:182]: Keep line width within 80 chars.

File: cdc/owner/changefeed.go [hunk 15]
```diff
@@ -262,12 +261,12 @@ LOOP:
...
+
 	cancelCtx, cancel := cdcContext.WithCancel(ctx)
 	c.cancel = cancel
-	c.sink, err = c.newSink(cancelCtx)
-	if err != nil {
-		return errors.Trace(err)
-	}
+
+	c.sink = c.newSink()
+	c.sink.run(ctx, ctx.ChangefeedVars().ID, ctx.ChangefeedVars().Info)
```
Comment (amyangfei) [inline cdc/owner/changefeed.go:269]: Any difference between using `ctx` and `cancelCtx` here?

**Comment by hi-rustin** [comment]
> fix owner may be blocked when initializing the changefeed.

@3AceShowHand Can you fix your release note? It is not a valid release note.
1. it does not start with a capital
2. it doesn't make it clear what blocking is occurring during initialization
3. it should not have a period
