### PR TITLE
*: fix many goroutine leak

### LINKED ISSUE #1025: The memory and goroutine leak when PD leader switched
## Bug Report

Please answer these questions before submitting your issue. Thanks!

A user report that the CPU usage of CDC owner periodic increase
image

After some initial investigation, I found that the cpu is occupied by gc. And there is a memory and goroutine leak in TiCDC owner

### PR DESCRIPTION
**Pull request by leoppro**
### What problem does this PR solve? 
 fix 6 goroutine leaks in TiCDC fix #1025

a goroutine leak in tidb client is found by this test pingcap/tidb#20654

before this PR:

企业微信截图_10ec311a-66fd-4bf5-abf5-efd2e4f2903d

after this PR:
image

### Release note

- Fix many goroutine leaks.

### CODE REVIEW

File: cdc/changefeed.go [hunk 1]
```diff
@@ -20,6 +20,8 @@ import (
 	"sync"
 	"time"
 
+	tidbkv "github.com/pingcap/tidb/kv"
+
```
Comment (overvenus) [inline cdc/changefeed.go:24]:
```suggestion
	tidbkv "github.com/pingcap/tidb/kv"
```

File: pkg/notify/notify.go [hunk 2]
```diff
@@ -60,7 +60,12 @@ func (r *Receiver) signalNonBlocking() bool {
 func (r *Receiver) signalTickLoop() {
 	go func() {
 	loop:
-		for range r.ticker.C {
+		for {
+			select {
+			case <-r.closeCh:
+				break
+			case <-r.ticker.C:
+			}
```
Comment (overvenus) [inline pkg/notify/notify.go:68]: Does it cause performance regression?

**Review by overvenus — COMMENTED** [review]
Could you use tidb/util/testleak to check leaks?

https://github.com/pingcap/tidb/tree/master/util/testleak

File: pkg/notify/notify.go (hunk 2 above)
Comment (leoppro) [reply pkg/notify/notify.go:68]: This won't be a performance bottleneck here theoretically.

File: cdc/owner.go [hunk 3]
```diff
@@ -343,7 +338,11 @@ func (o *Owner) newChangeFeed(
...
 	go func() {
-		err := <-errCh
+		var err error
+		select {
+		case <-ctx.Done():
+		case err = <-errCh:
+		}
 		if errors.Cause(err) != context.Canceled {
 			log.Error("error on running owner", zap.Error(err))
 		} else {
```
Comment (amyangfei) [inline cdc/owner.go:348]: If the branch `<-ctx.Done()` is fired, `err` is nil in L347, the error log is not as wished.

File: cdc/owner.go [hunk 4]
```diff
@@ -205,11 +204,7 @@ func (o *Owner) newChangeFeed(
 		failpoint.Return(nil, errors.New("failpoint injected retriable error"))
 	})
 
-	// TODO here we create another pb client,we should reuse them
-	kvStore, err := kv.CreateTiStore(strings.Join(o.pdEndpoints, ","), o.credential)
-	if err != nil {
-		return nil, err
-	}
+	kvStore := util.KVStorageFromCtx(ctx)
```
Comment (overvenus) [inline cdc/owner.go:207]: Is kvstorage thread-safe?

Comment (leoppro) [reply cdc/owner.go:207]: yes, and the recommended usage is to use him as a singleto.

File: cdc/owner.go (hunk 3 above)
Comment (leoppro) [reply cdc/owner.go:348]: Yes, but I haven't any better solution. And when the ctx is done, the error from the sink must be canceled.

Comment (amyangfei) [reply cdc/owner.go:348]: I mean if `ctx.Done` is triggered first, the errCh is not fetched and `err` is nil, we should log as normal exit then.

Comment (leoppro) [reply cdc/owner.go]: updated

**Review by amyangfei — COMMENTED** [review]
LGTM

File: cdc/kv/client.go [hunk 5]
```diff
@@ -351,12 +351,14 @@ func (c *CDCClient) newStream(ctx context.Context, addr string, storeID uint64)
 		}
 		err = version.CheckStoreVersion(ctx, c.pd, storeID)
 		if err != nil {
+			conn.Close()
```
[the remark this answers is not in the document]
Comment (leoppro) [reply cdc/kv/client.go:354]: emmm. I have not idea...

**Comment by overvenus** [comment]
LGTM

**Review by ti-srebot — APPROVED** [review]

File: cdc/owner.go (hunk 4 above)
Comment (overvenus) [reply cdc/owner.go:207]: So what about a global variable?
