### PR TITLE
schemaStorage: reduce memory usage and add unit tests

### LINKED ISSUE #1098: TiCDC costs too much memory if table count is large or DDL is frequent
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

   In one user's scenario:

   - there exists about 1000 tables in upstream
   - DDL operation is frequent
   - Each DDL could involve hundreds of tables.

2. What did you expect to see?

    Replication is normal

3. What did you see instead?

    - TiCDC costs too much memory and could be OOM, for some reasons

      - Although changefeed only replicates part of tables, all tables' information is cached in memory.
      - TiCDC owner executes DDL one by one, so the schema versions could be cached too many in `processor`, and GC is delayed because of the DDL execution latency. Such as upstream executes 100 DDLs in sequence, TiCDC could cache 101 copies of schema version at most.

    - memory profile: [heap.log](https://github.com/pingcap/ticdc/files/5564822/heap.log)

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        v4.0.8
        ```

    - TiCDC version (execute `cdc version`):

        ```
        v4.0.8
        ```

### PR DESCRIPTION
**Pull request by leoppro**
### What problem does this PR solve? 
fix #1098

* reduce memory usage in schema storage by avoiding table info replication
* add many unit tests

500 table created:
before this PR:
image

after this PR:
image

### Check List 

Tests 

 - Unit test
 - Integration test

### CODE REVIEW

File: cdc/entry/schema_storage.go [hunk 1]
```diff
@@ -223,13 +227,21 @@ func (s *schemaSnapshot) Clone() *schemaSnapshot {
 
 	tables := make(map[int64]*model.TableInfo, len(s.tables))
 	for k, v := range s.tables {
-		tables[k] = v.Clone()
+		tables[k] = v
```
Comment (amyangfei) [inline cdc/entry/schema_storage.go:230]: Is it safe to change L224 to `schemas[k] = v`.

The behavior is to change `TableInfo` when applying DDL changes, better to leave some comments here about the principle and comments the function is not a totally `Clone`.

File: cdc/entry/schema_storage_test.go [hunk 2]
```diff
@@ -770,3 +777,195 @@ func (t *schemaSuite) TestExplicitTables(c *check.C) {
...
+			snapFromMeta, err := newSchemaSnapshotFromMeta(meta, ts, false)
+			c.Assert(err, check.IsNil)
+			snapFromSchemaStore, err := scheamStorage.GetSnapshot(ctx, ts)
+			c.Assert(err, check.IsNil)
+
+			tidySchemaSnapshot(snapFromMeta)
+			tidySchemaSnapshot(snapFromSchemaStore)
+			// check if the two snapshot are equal.
+			checkSnapsEquals(snapFromMeta, snapFromSchemaStore)
+		}
```
Comment (amyangfei) [inline cdc/entry/schema_storage_test.go:907]: Could we also check the historical snapshot from the `schemaStorage`, such as querying by `ts-1` or last job FinishedTs

**Comment by zhangjinpeng1987** [comment]
How about 10K tables? Maybe we should load the table schema lazily? Using the LRU strategy?

**Comment by leoppro** [comment]
> How about 10K tables? Maybe we should load the table schema lazily? Using the LRU strategy?

The way to reduce memory usage in this PR is cheap and effective.
To support 10K tables, only reduce the memory usage is not enough. We need to consider memory, ETCD access frequency, and so on. We have a plan to solve the problem by optimizing the replication model.

File: cdc/entry/schema_storage.go [hunk 3]
```diff
@@ -376,18 +384,20 @@ func (s *schemaSnapshot) createSchema(db *timodel.DBInfo) error {
 		return cerror.ErrSnapshotSchemaExists.GenWithStackByArgs(db.Name, db.ID)
 	}
 
-	s.schemas[db.ID] = db.Clone()
```
Comment (amyangfei) [inline cdc/entry/schema_storage.go:379]: Is it better to keep this `Clone`, and the `DDL job` can be recycled

File: cdc/entry/schema_storage.go [hunk 4]
```diff
@@ -376,18 +384,20 @@ func (s *schemaSnapshot) createSchema(db *timodel.DBInfo) error {
...
 	return nil
 }
 
 func (s *schemaSnapshot) replaceSchema(db *timodel.DBInfo) error {
-	if _, ok := s.schemas[db.ID]; !ok {
+	_, ok := s.schemas[db.ID]
+	if !ok {
 		return cerror.ErrSnapshotSchemaNotFound.GenWithStack("schema %s(%d) not found", db.Name, db.ID)
 	}
-	s.schemas[db.ID] = db.Clone()
```
Comment (amyangfei) [inline cdc/entry/schema_storage.go:390]: ditto

File: cdc/entry/schema_storage.go [hunk 5]
```diff
@@ -376,18 +384,20 @@ func (s *schemaSnapshot) createSchema(db *timodel.DBInfo) error {
 		return cerror.ErrSnapshotSchemaExists.GenWithStackByArgs(db.Name, db.ID)
 	}
 
-	s.schemas[db.ID] = db.Clone()
+	s.schemas[db.ID] = db
```
Comment (leoppro) [inline cdc/entry/schema_storage.go:387]:
```suggestion
	s.schemas[db.ID] = db.Clone()
```

File: cdc/entry/schema_storage.go [hunk 6]
```diff
@@ -376,18 +384,20 @@ func (s *schemaSnapshot) createSchema(db *timodel.DBInfo) error {
...
 }
 
 func (s *schemaSnapshot) replaceSchema(db *timodel.DBInfo) error {
-	if _, ok := s.schemas[db.ID]; !ok {
+	_, ok := s.schemas[db.ID]
+	if !ok {
 		return cerror.ErrSnapshotSchemaNotFound.GenWithStack("schema %s(%d) not found", db.Name, db.ID)
 	}
-	s.schemas[db.ID] = db.Clone()
+	s.schemas[db.ID] = db
```
Comment (leoppro) [inline cdc/entry/schema_storage.go:400]:
```suggestion
	s.schemas[db.ID] = db.Clone()
```

**Review by amyangfei — COMMENTED** [review]
LGTM

**Comment by liuzix** [comment]
LGTM

**Review by ti-srebot — APPROVED** [review]
