### PR TITLE
mounter(ticdc): fix mounter add default value type unsupported

### LINKED ISSUE #3793: upgrade from v4.0.15 to v4.0.16, ticdc stoped with CDC:ErrProcessorUnknown
### What did you do?

1. in v4.0.15, set cdc changefeed, write data
2. upgrade to v4.0.16
3. write data
4. scale-out tidb,pd,tikv
5. scale-in tidb/pd/tikv
6. check CDC status

upstream: tidb
downstream: tidb

### What did you expect to see?

task works normal

### What did you see instead?

task stopped at "2021-12-08 14:08:26.157"
[
  {
    "id": "simple-cdc-task",
    "summary": {
      "state": "normal",
      "tso": 429639258906820611,
      "checkpoint": "2021-12-08 14:08:26.157",
      "error": {
        "addr": "cdc-peer:8300",
        "code": "CDC:ErrProcessorUnknown",
        "message": "[CDC:ErrReachMaxTry]reach maximum try: 8"
      }
    }
  }
]
[root@cdc-0 bin]# date
Wed Dec  8 16:09:36 CST 2021
[root@cdc-0 bin]# 
[cdc.log.gz](https://github.com/pingcap/ticdc/files/7676020/cdc.log.gz)

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
-------+
| Release Version: v4.0.16
Edition: Community
Git Commit Hash: 75f81d2d7faae72575c4e471ec0b96756796284a
Git Branch: heads/refs/tags/v4.0.16
UTC Build Time: 2021-12-02 04:17:32
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |

```

TiCDC version (execute `cdc version`):

```console
[root@cdc-0 bin]# ./cdc version
Release Version: v4.0.16
Git Commit Hash: 6283ec07544ee7011c52aad154bf93a0ee412fa4
Git Branch: heads/refs/tags/v4.0.16
UTC Build Time: 2021-12-02 13:07:10
Go Version: go version go1.13 linux/amd64
Failpoint Build: false


```

### PR DESCRIPTION
**Pull request by maxshuang**
close  #3793

### What problem does this PR solve? 
Fix default value  unsupported bug cause by amend feature of tidb, related to issue #3793

Amend feature of TiDB:
As for add column DDL, if a DDL occur between a trx, the trx will not redo but commit the old schema data directly, which will cause TiCDC use new schema to parse old schema data.

### What is changed and how it works?
After call "getDefaultOrZeroValue", we need to call "formatColVal" to format data from the tidb type to go supported sql type

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
Start 2 transactions:

1. Transaction 1:
```
Create table test_column(id int primary key);
Insert Into test_column values(1);
begin;
Insert Into test_column values(2);
// hold the trx untill Transaction 2 commit DDL
commit;
```

- Transaction 2:
```
alter table test_column add column c0 date not null;
```
Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to update key monitor metrics in both TiCDC document and official document

### Release note 

```release-note
Fix mounter default date value not support
```

### CODE REVIEW

File: cdc/entry/mounter.go [hunk 1]
```diff
@@ -490,36 +489,36 @@ func formatColVal(datum types.Datum, tp byte) (
...
+		// Go sql support type ref to: https://github.com/golang/go/blob/go1.17.4/src/database/sql/driver/types.go#L236
 		return datum.GetValue(), sizeOfDatum(datum), "", nil
 	}
 }
 
-func getDefaultOrZeroValue(col *timodel.ColumnInfo) (interface{}, int) {
-	// see https://github.com/pingcap/tidb/issues/9304
-	// must use null if TiDB not write the column value when default value is null
-	// and the value is null
+func getDefaultOrZeroValue(col *timodel.ColumnInfo) (interface{}, int, string, error) {
```
Comment (overvenus) [inline cdc/entry/mounter.go:499]: Could you add some comments to list all possible results behind the `interface{}`? Also add to `formatColVal` and `model.Column.Value`.

File: cdc/entry/mounter_test.go [hunk 2]
```diff
@@ -423,3 +425,308 @@ func walkTableSpanInStore(t *testing.T, store tidbkv.Storage, tableID int64, f f
 		require.Nil(t, err)
 	}
 }
+
+// Check following MySQL type, ref to :
```
Comment (overvenus) [inline cdc/entry/mounter_test.go:429]:
```suggestion
// Check following MySQL type, ref to
```

**Review by overvenus — COMMENTED** [review]
Rest LGTM

File: cdc/entry/mounter.go (hunk 1 above)
Comment (maxshuang) [reply cdc/entry/mounter.go:499]: Get. OK.

File: cdc/entry/mounter_test.go [hunk 3]
```diff
@@ -423,3 +425,308 @@ func walkTableSpanInStore(t *testing.T, store tidbkv.Storage, tableID int64, f f
...
+			},
+			Res: nil,
+		},
+	}
+	testGetDefaultZeroValue(t, colAndRess)
+}
+
+func testGetDefaultZeroValue(t *testing.T, colAndRess []columnInfoAndResult) {
+	for _, colAndRes := range colAndRess {
+		val, _, _, _ := getDefaultOrZeroValue(&colAndRes.ColInfo)
```
Comment (amyangfei) [inline cdc/entry/mounter_test.go:729]: Better to check the other return values

File: cdc/entry/mounter_test.go [hunk 4]
```diff
@@ -423,3 +425,308 @@ func walkTableSpanInStore(t *testing.T, store tidbkv.Storage, tableID int64, f f
...
+			{
+				ColInfo: timodel.ColumnInfo{
+					FieldType: types.FieldType{
+						Tp:   mysql.TypeEnum,
+						Flag: mysql.NotNullFlag,
+					},
+				},
+				Res: int64(0),
+			},
+		*/
```
Comment (amyangfei) [inline cdc/entry/mounter_test.go:702]: why this case panic?

Comment (maxshuang) [reply cdc/entry/mounter_test.go:702]: I already fix it.

File: cdc/entry/mounter_test.go (hunk 3 above)
Comment (maxshuang) [reply cdc/entry/mounter_test.go:728]: May need more unit tests also. I will add more in other pr.

File: cdc/entry/mounter.go [hunk 5]
```diff
@@ -490,36 +490,39 @@ func formatColVal(datum types.Datum, tp byte) (
 		const sizeOfV = unsafe.Sizeof(v)
 		return v, int(sizeOfV), warn, nil
 	default:
+		// NOTICE: GetValue() may return some types that go sql not support, which will cause sink DML fail
```
Comment (overvenus) [inline cdc/entry/mounter.go:493]:
```suggestion
		// FIXME: GetValue() may return some types that go sql not support, which will cause sink DML fail
```

**Review by overvenus — APPROVED** [review]
LGTM

**Review by amyangfei — APPROVED** [review]
