### PR TITLE
codec: fix the open protocol flag

### LINKED ISSUE #1227: kafka integration test since open protocol flag is incorrect
Run the following SQL:
```
create table t(id int primary key)
insert into t values (1)
```

The tiflow result:
```
{"u":{"id":{"t":3,"h":true,"f":11,"v":1}}}
```

The ticdc result:
```
{"u":{"id":{"t":3,"h":true,"f":4099,"v":1}}}
```

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### What problem does this PR solve?

Issue Number: close #1227 

### What is changed and how it works?

* Changing the column Flag type from uint to uint64 and updating related flag-check calls to use new helper functions (e.g. isBinary, isUnsigned, isPrimary).
* Introducing a column flags caching mechanism in the batch encoder to improve flag calculation efficiency.
* Adjusting encoding and decoding logic to properly pass the computed column flags.

#### Tests 

- Unit test
- Integration test

### Release note 

```release-note
`None`
```

### CODE REVIEW

File: pkg/sink/codec/open/encoder.go [hunk 1]
```diff
@@ -61,13 +64,23 @@ func (d *batchEncoder) Clean() {
 	}
 }
 
+func (d *batchEncoder) fetchColumnFlags(e *commonEvent.RowEvent) map[string]uint64 {
+	result, ok := d.columnFlagsCache[e.GetTableID()]
```
Comment (wk989898) [inline pkg/sink/codec/open/encoder.go:68]: Why cache column flag? It looks better to use a map to convert flag into columnFlag.

File: pkg/sink/codec/open/decoder.go [hunk 2]
```diff
@@ -251,7 +251,7 @@ func buildColumns(
 			Value: value,
 		}
 		if _, ok := handleKeyColumns[name]; ok {
-			col.Flag = mysql.PriKeyFlag
+			col.Flag |= binaryFlag
```
Comment (wk989898) [inline pkg/sink/codec/open/decoder.go:254]: Why use a binary flag?

Comment (3AceShowHand) [reply pkg/sink/codec/open/decoder.go:254]: it's found a binary flag.

File: pkg/sink/codec/open/encoder.go (hunk 1 above)
Comment (3AceShowHand) [reply pkg/sink/codec/open/encoder.go:68]: the columnFlag is calculated by the flag, and cache it to prevent calculation on each message

File: pkg/sink/codec/open/message.go [hunk 3]
```diff
@@ -206,3 +207,117 @@ func (m *messageRow) decode(data []byte) {
...
+		for _, idxCol := range idxInfo.Columns {
+			flag := result[idxCol.Name.O]
+			if idxInfo.Primary {
+				flag |= primaryKeyFlag
+			} else if idxInfo.Unique {
+				flag |= uniqueKeyFlag
+			}
+			if len(idxInfo.Columns) > 1 {
+				flag |= multipleKeyFlag
+			}
```
Comment (wk989898) [inline pkg/sink/codec/open/message.go:314]: Please keep same with simple protocol. https://github.com/pingcap/ticdc/blob/39a11cc09049b6685fe647a7ba603728150b10f6/pkg/sink/codec/simple/decoder.go#L413-L426

**Review by wk989898 — APPROVED** [review]
