### PR TITLE
sink: fix atomicity of transactions is broken

### LINKED ISSUE #1359: Atomicity of transactions is broken in the downstream when using async commit
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

    Test CDC with https://github.com/pingcap/tipocket/pull/348 with async commit enabled. The test runs bank transfers in the upstream checks sum in the downstream.

2. What did you expect to see?

    The balance sum in the downstream should always be the same.

3. What did you see instead?

    The balance sum in the downstream is changed. From the log, we see that the atomicity of some transactions is broken.

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        TiDB: 7b79af93d7949eb3abd1ea411f8e65cecf430301
        TiKV: 6fbe59e2a504ed3a5243558c6aa59d9a8664ce44
        PD: c15cb77a17307674e21bfffad3b7911c50f9eb52

    - TiCDC version (execute `cdc version`):

        ```
        Release Version: v4.0.2-289-g33b871e
        Git Commit Hash: 33b871e798ec4b9345ec50c3b431831ac67b9a45
        Git Branch: master
        UTC Build Time: 2021-01-17 22:17:22
        Go Version: go version go1.14.13 linux/amd64
        ```

Some more logs:

[tpctl-cdc-bank-universal-smx5x.tar.gz](https://github.com/pingcap/ticdc/files/5878792/tpctl-cdc-bank-universal-smx5x.tar.gz)

### PR DESCRIPTION
**Pull request by leoppro**
### What problem does this PR solve? 
fix #1359 

### Check List 

Tests 

 - Unit test
 - Integration test

### Release note

- fix atomicity of transactions is broken in the downstream

### CODE REVIEW

File: cdc/sink/common/common_test.go [hunk 1]
```diff
@@ -29,70 +31,131 @@ var _ = check.Suite(&SinkCommonSuite{})
...
-		unresolvedTxns         map[model.TableID][]*model.SingleTableTxn
-		resolvedTs             uint64
-		expectedResolvedTxns   map[model.TableID][]*model.SingleTableTxn
-		expectedUnresolvedTxns map[model.TableID][]*model.SingleTableTxn
-		expectedMinTs          uint64
-	}{{
-		unresolvedTxns: map[model.TableID][]*model.SingleTableTxn{
-			1: {{CommitTs: 11}, {CommitTs: 21}, {CommitTs: 21}, {CommitTs: 23}, {CommitTs: 33}, {CommitTs: 34}},
-			2: {{CommitTs: 23}, {CommitTs: 24}, {CommitTs: 26}, {CommitTs: 26}, {CommitTs: 26}, {CommitTs: 29}},
+	testCases := [][]struct {
```
Comment (amyangfei) [inline cdc/sink/common/common_test.go:34]: Please add comment to the test goal of each case

Comment (leoppro) [reply cdc/sink/common/common_test.go:34]: PTAL again

File: cdc/sink/common/common.go [hunk 2]
```diff
@@ -24,17 +24,43 @@ import (
...
+		t.txns[row.StartTs] = txn
+	}
+	txn.Append(row)
+}
+
 // UnresolvedTxnCache caches unresolved txns
 type UnresolvedTxnCache struct {
 	unresolvedTxnsMu sync.Mutex
-	unresolvedTxns   map[model.TableID][]*model.SingleTableTxn
+	unresolvedTxns   map[model.TableID][]txnsWithTheSameCommitTs
```
Comment (amyangfei) [inline cdc/sink/common/common.go:56]: Please add some comments about the design principle of txn cache, such as
- the intput of txn cache is `CommitTs` strictly increasing
- why txn is grouped by `CommitTs`, and then grouped by `StartTs`

Comment (leoppro) [reply cdc/sink/common/common.go:56]: PTAL again

**Comment by liuzix** [comment]
LGTM

**Comment by amyangfei** [comment]
meet an irrelevant ci failure
```
[2021-01-28T07:42:33.564Z] [2021/01/28 15:39:59.725 +08:00] [ERROR] [pipeline.go:74] ["found error when running the node"] [name="error node"] [error="error node throw an error, index: 3"] [errorVerbose="error node throw an error, index: 3\ngithub.com/pingcap/ticdc/pkg/pipeline.(*errorNode).Receive\n\t/home/jenkins/agent/workspace/cdc_ghpr_leak_test/go/src/github.com/pingcap/ticdc/pkg/pipeline/pipeline_test.go:196\ngithub.com/pingcap/ticdc/pkg/pipeline.(*nodeRunner).run\n\t/home/jenkins/agent/workspace/cdc_ghpr_leak_test/go/src/github.com/pingcap/ticdc/pkg/pipeline/runner.go:60\ngithub.com/pingcap/ticdc/pkg/pipeline.(*Pipeline).driveRunner\n\t/home/jenkins/agent/workspace/cdc_ghpr_leak_test/go/src/github.com/pingcap/ticdc/pkg/pipeline/pipeline.go:70\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357"] [stack="github.com/pingcap/ticdc/pkg/pipeline.(*Pipeline).driveRunner\n\t/home/jenkins/agent/workspace/cdc_ghpr_leak_test/go/src/github.com/pingcap/ticdc/pkg/pipeline/pipeline.go:74"]
[2021-01-28T07:42:33.564Z] 
[2021-01-28T07:42:33.564Z] ----------------------------------------------------------------------
[2021-01-28T07:42:33.564Z] FAIL: pipeline_test.go:287: pipelineSuite.TestPipelineThrow
[2021-01-28T07:42:33.564Z] 
[2021-01-28T07:42:33.564Z] pipeline_test.go:283:
[2021-01-28T07:42:33.564Z]     n.c.Assert(n.index, check.Equals, 6)
[2021-01-28T07:42:33.564Z] ... obtained int = 4
[2021-01-28T07:42:33.564Z] ... expected int = 6
[2021-01-28T07:42:33.564Z] 
[2021-01-28T07:42:33.564Z] pipeline_test.go:315:
[2021-01-28T07:42:33.564Z]     c.Assert(len(errs), check.Equals, 4)
[2021-01-28T07:42:33.564Z] ... obtained int = 2
[2021-01-28T07:42:33.564Z] ... expected int = 4
[2021-01-28T07:42:33.564Z] 
[2021-01-28T07:42:33.564Z] OOPS: 2 passed, 1 FAILED
[2021-01-28T07:42:33.564Z] --- FAIL: TestSuite (0.08s)
[2021-01-28T07:42:33.564Z] FAIL
[2021-01-28T07:42:33.564Z] FAIL	github.com/pingcap/ticdc/pkg/pipeline	0.122s
```

File: cdc/sink/common/common.go [hunk 3]
```diff
@@ -88,40 +117,44 @@ func (c *UnresolvedTxnCache) Resolved(resolvedTs uint64) map[model.TableID][]*mo
...
+		var resolvedTxnsWithTheSameCommitTs []txnsWithTheSameCommitTs
 		if i == len(txns) {
-			resolvedTxns = txns
+			resolvedTxnsWithTheSameCommitTs = txns
 			delete(unresolvedTxns, tableID)
 		} else {
-			resolvedTxns = txns[:i]
+			resolvedTxnsWithTheSameCommitTs = txns[:i]
 			unresolvedTxns[tableID] = txns[i:]
 		}
```
Comment (amyangfei) [inline cdc/sink/common/common.go:144]: `unresolvedTxns` holds a slice of struct  `txnsWithTheSameCommitTs`, copy could happen easily and have performance degradation. Suggest to use struct pointer in slice, or we can have a benchmark

**Review by amyangfei — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
