### PR TITLE
owner: check if the checkpoint ts is less then gc safe time when create the changefeed

### LINKED ISSUE #1014: CDC should not work if changefeed's checkpoint is earlier than current gc safepoint
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

* Create a changefeed
* Stop CDC server for more than 24h so that the service safepoint is expired and invalidated, and the data after that time is gc-ed.
* Start CDC server

2. What did you expect to see?

The changefeed is broken and should not be able to continue

3. What did you see instead?

CDC still tries to continue the changefeed and sets a service safepoint at the checkpoint, which is before the current actual gc safepoint.

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        4.0.4
        ```

    - TiCDC version (execute `cdc version`):

        ```
        4.0.4
        ```

    I didn't confirm if this bug still exist in current version, but I suspect it does.

### PR DESCRIPTION
**Pull request by leoppro**
### What problem does this PR solve? 
check if the checkpoint ts is less then gc safe time when create the changefeed
fix #1014 

### Check List 

Tests 

 - Integration test
the `changefeed_error` test in the current integration test is already do good.
 - Manual test (add detailed scripts or steps below)
try to follow the step in #1014, we can see the owner throw an error immediately for now.

### Release note

- No release note

### CODE REVIEW

File: cdc/kv/etcd.go [hunk 1]
```diff
@@ -853,3 +855,22 @@ func (c CDCEtcdClient) GetOwnerID(ctx context.Context, key string) (string, erro
 	}
 	return string(resp.Kvs[0].Value), nil
 }
+
+// GetGCSafePoint get tikv GC safe point
+func (c CDCEtcdClient) GetGCSafePoint(ctx context.Context) (uint64, error) {
+	resp, err := c.Client.Get(ctx, tikv.GcSavedSafePoint)
```
Comment (overvenus) [inline cdc/kv/etcd.go:861]: Could you get gc safepoint by `pd_client.UpdateGCSafePoint(0)`?

File: cdc/owner.go [hunk 2]
```diff
@@ -186,16 +186,16 @@ func (o *Owner) addOrphanTable(cid model.CaptureID, tableID model.TableID, start
...
 	log.Info("Find new changefeed", zap.Stringer("info", info),
 		zap.String("id", id), zap.Uint64("checkpoint ts", checkpointTs))
-
+	safePoint, err := cli.GetGCSafePoint(ctx)
+	if err != nil {
+		return nil, errors.Trace(err)
+	}
+	if checkpointTs < safePoint {
+		return nil, tikv.ErrGCTooEarly.GenWithStackByArgs(checkpointTs, safePoint)
+	}
```
Comment (overvenus) [inline cdc/owner.go:198]: Please add a **unit** test. (Test newChangeFeed is enough)

**Comment by overvenus** [comment]
Could you move this forward? tikv/pd#3136 does not block this fix I think.

**Comment by leoppro** [comment]
> Could you move this forward? [tikv/pd#3136](https://github.com/tikv/pd/issues/3136) does not block this fix I think.

If tikv/pd#3136 is not fixed, cdc will throw an error when create a changefeed, because cdc can't get gc safetime before the gc worker running first time.

File: pkg/util/gc_service.go [hunk 3]
```diff
@@ -0,0 +1,43 @@
...
+	"github.com/pingcap/errors"
+	"github.com/pingcap/tidb/store/tikv"
+	pd "github.com/tikv/pd/client"
+)
+
+const (
+	// CDCChangefeedCreatingServiceGCSafePointID is service GC safe point ID
+	CDCChangefeedCreatingServiceGCSafePointID = "ticdc-changefeed-creating"
+	// CDCChangefeedCreatingServiceGCSafePointTTL is service GC safe point TTL
+	CDCChangefeedCreatingServiceGCSafePointTTL = 10 * 60 // 10 mins
```
Comment (amyangfei) [inline pkg/util/gc_service.go:28]: Not necessary to export these two variables

File: cmd/util.go [hunk 4]
```diff
@@ -22,10 +22,11 @@ import (
 	"net/url"
 	"os"
 	"os/signal"
-	"strconv"
 	"strings"
 	"syscall"
 
+	"github.com/pingcap/ticdc/pkg/util"
+
```
Comment (overvenus) [inline cmd/util.go:29]:
```suggestion
	"github.com/pingcap/ticdc/pkg/util"
```

**Comment by leoppro** [comment]
@amyangfei PTAL @liuzix

**Review by amyangfei — COMMENTED** [review]
LGTM

File: pkg/util/gc_service_test.go [hunk 5]
```diff
@@ -0,0 +1,171 @@
...
+	"context"
+	"math"
+
+	"github.com/pingcap/check"
+	"github.com/pingcap/kvproto/pkg/metapb"
+	"github.com/pingcap/kvproto/pkg/pdpb"
+	pd "github.com/tikv/pd/client"
+)
+
+type gcServiceuite struct {
```
Comment (overvenus) [inline pkg/util/gc_service_test.go:26]:
```suggestion
type gcServiceSuite struct {
```

File: pkg/util/gc_service_test.go [hunk 6]
```diff
@@ -0,0 +1,171 @@
...
+	s.pdCli.UpdateServiceGCSafePoint(ctx, "service2", 10, 80) //nolint:errcheck
+	s.pdCli.UpdateServiceGCSafePoint(ctx, "service3", 10, 70) //nolint:errcheck
+	err = CheckSafetyOfStartTs(ctx, s.pdCli, 65)
+	c.Assert(err, check.IsNil)
+	c.Assert(s.pdCli.serviceSafePoint, check.DeepEquals, map[string]uint64{"service1": 60, "service2": 80, "service3": 70, "ticdc-changefeed-creating": 65})
+
+}
+
+type mockPdClientForServiceGCSafePoint struct {
+	baseMockPdClient
```
Comment (overvenus) [inline pkg/util/gc_service_test.go:48]:
```suggestion
	pd.Client
```

How about this? So that we do not need to impl all methods.

File: pkg/config/config.go [hunk 7]
```diff
@@ -25,8 +25,9 @@ import (
 )
 
 var defaultReplicaConfig = &ReplicaConfig{
-	CaseSensitive:  true,
-	EnableOldValue: false,
+	CaseSensitive:    true,
+	EnableOldValue:   false,
+	CheckGCSafePoint: true,
```
Comment (overvenus) [inline pkg/config/config.go:30]: Why add flag? I think it must be checked all the time.

Comment (leoppro) [reply pkg/config/config.go:30]: cause of the bug in pd (tikv/pd#3128), if TiCDC(4.0.9+) try to connect to a TiKV(which of the version is less then 4.0.8), the gc safe point check will failed. so we add a flag to skip the check

Comment (overvenus) [reply pkg/config/config.go:30]: What about checking GC safepoint by cluster version automatically?

Comment (leoppro) [reply pkg/config/config.go:30]: It's not strict I think. the version check is not correct all the time(for example : the version of a binary built in the master branch may be 4.0.x-xxx-dirty)

Comment (leoppro) [reply pkg/config/config.go:30]: and multi-version components in one cluster are not recommended for production. I think it's enough that we just make sure that the cdc is able to connect to the old version tikv

**Comment by overvenus** [comment]
LGTM

**Review by ti-srebot — APPROVED** [review]
