### PR TITLE
fix the memory leak in sink manager (#1401)

### LINKED ISSUE #1398: Memory is not released after incremental scan finished
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

   1. pause a changefeed for a long time, and some data is accumulated
   2. resume the changefeed, there will be some incremental scan data
   3. After the incremental scan is finished, observe the heap memory usage of cdc server (No incremental data in upstream)

2. What did you expect to see?

     Heap memory decreases after the incremental scan is finished (may have some latency because of Go GC)

3. What did you see instead?

    1. changefeed resume happens at 18:18:00
    2. note at 2021-02-03 00:34:00, the changefeed is scheduled away from `172.16.4.128:8301`, so the memory usage decreased.

    </img>
    </img>

   Grafana snapshot:  [Test-Cluster-TiCDC-0002_2021-02-03T05_26_28.241Z.zip](https://github.com/pingcap/ticdc/files/5916332/Test-Cluster-TiCDC-0002_2021-02-03T05_26_28.241Z.zip)
    
   Heap dump: [heap.zip](https://github.com/pingcap/ticdc/files/5916340/heap.zip)

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        v4.0.10
        ```

    - TiCDC version (execute `cdc version`):

        ```
        release-4.0 @ b82898697161967412107b4920a7bd03a5688dff
        ```

        confirmed `v4.0.10` is not affected

### PR DESCRIPTION
**Pull request by leoppro**
### What problem does this PR solve? 

fix the memory leak in sink manager, this bug is import by #1247 , fix #1398

### What is changed and how it works?

https://github.com/pingcap/ticdc/blob/6febbae2ec0425fcad6ad74a0644ec595ccc0189/cdc/sink/manager.go#L149

image

- The blue squares represent the space referenced by `t.buffer`
- The yellow squares represent space that has been discarded by the `t.buffer`
- All squares that are not white hold a reference of `RowChangeEvnet`

The yellow squares is unreachable but can't be GC, because the `b.buffer` reference the `array` and the `array` include the yellow squares, the GO GC can't reclaim this space.

### Check List 

Tests 

 - Unit test
 - Integration test

### Release note

- No release note

### CODE REVIEW

**Review by amyangfei — COMMENTED** [review]
LGTM

File: cdc/sink/manager.go [hunk 1]
```diff
@@ -146,7 +146,7 @@ func (t *tableSink) FlushRowChangedEvents(ctx context.Context, resolvedTs uint64
 		return t.manager.flushBackendSink(ctx)
 	}
 	resolvedRows := t.buffer[:i]
-	t.buffer = t.buffer[i:]
+	t.buffer = append(make([]*model.RowChangedEvent, 0, len(t.buffer[i:])), t.buffer[i:]...)
```
Comment (overvenus) [inline cdc/sink/manager.go:149]: Could you add a unit test to make sure the buffer length is under a reasonable value?

**Comment by amyangfei** [comment]
PTAL @overvenus @liuzix

**Review by amyangfei — APPROVED** [review]

**Review by ti-srebot — APPROVED** [review]
